### ISSUE TITLE
Hidden state violates Redux contract

### ISSUE THREAD

**Issue by gaearon** [omnidan/redux-undo#1]
Redux store enhancers should avoid keeping local state as much as possible. The current implementation puts history into `store._history`. This causes it to [break with redux-devtools](https://github.com/gaearon/redux-devtools/pull/116#issuecomment-141255121).

The real solution is to **keep actions *and* current state as part of the `state` managed by reducer**. This means that the state managed by reducer wrapped in `undo` higher-order reducer will have

```js
{
  currentState: ... // actual state the app should subscribe to
  history: [] // actions
}
```

structure.

**Comment by omnidan** [comment]
Thank you so much again. Your solution is much cleaner.

**Comment by gaearon** [comment]
Thanks!
You might be inspired by https://github.com/evancz/elm-architecture-tutorial/

**Comment by omnidan** [comment]
@gaearon I already started reading about elm, just haven't got enough time to really start using it :sweat_smile: It's really cool though.
