### ISSUE TITLE
make contributing easier

### ISSUE THREAD

**Issue by omnidan** [omnidan/redux-undo#101]
https://opensource.com/business/16/6/10-tips-new-github-projects
- [x] consider adding CONTRIBUTING.md and a template for issues/PRs
- [x] create `bitesize` label for issues (I think it's called something else on most projects, but the point is making it easy to contribute for beginners, e.g. documentation, small fixes, etc)
- [x] create documentation related issues (with `bitesize` labels)

**Comment by tiemevanveen** [comment]
Yeah that’s cool! Not sure if `bitesize` is the best.. but lots of project indeed do this. I think this would be mostly doc fixes for redux-undo but that doesn't matter.

**Comment by omnidan** [comment]
@tiemevanveen redux is mostly doc contributions too ;)

**Comment by tiemevanveen** [comment]
Nothing beats good doc contributions :)

**Comment by nmay231** [comment]
[Here](https://github.com/stevemao/github-issue-templates) is a collection of simple issue templates. We could grab one for now and change it later if we need to (maybe start with the [conversational templates?](https://github.com/stevemao/github-issue-templates/tree/master/conversational))

**Comment by omnidan** [comment]
@nmay231 I like the conversational templates! We can simply start using these for now and adjust them as we go.

**Comment by nmay231** [comment]
Perfect!
Templates are included in #247 and I added a "good first issue" label.

**Comment by nmay231** [comment]
"First-timers" issues created in #253 and #254 

We should also create a backlog and add it to the [documentation project](https://github.com/omnidan/redux-undo/projects/1).

But for now, this issue is closed :+1:
