### ISSUE TITLE
Empty future list after undoing action

### ISSUE THREAD

**Issue by imlgm** [omnidan/redux-undo#103]
![image](https://cloud.githubusercontent.com/assets/5555305/16866798/a71e2538-4aa0-11e6-8950-b92e0f368df8.png)

there is an empty future list in my app's state after i triggered unto action. I can't figure out what caused this. 

Following is my configuration: 

```
createStore(undoable(reducer, {
        limit: 20, 
        filter: (action) => {
            return undoableActions.indexOf(action) !== -1; 
        }, 
        undoType: EDITPANEL_UNDO, 
        redoType: EDITPANEL_REDO, 
        initTypes: ['@@redux-undo/INIT'], 
        debug: true, 
    }), UIBuilderState.get(stateKey), applyMiddleware(thunk));
```

Did I do something wrong?

**Comment by omnidan** [comment]
@imlgm could you provide a small example repo to make it easier to reproduce and fix this issue? something similar to this: https://github.com/peteruithoven/redux-undo-filtering-issue-example  would be perfect :grin:

**Comment by imlgm** [comment]
@omnidan OK, I will try, 
Because the project I run is a little complicated, and the project also used some private package. I am not sure whether I can reproduce the bug if I set up a new demo project.

**Comment by davidroeca** [comment]
I've fixed this in the following pull request: https://github.com/omnidan/redux-undo/pull/139

The problem in your case is that the present is filtered, and the old logic didn't allow for any state to be saved in the past or present if wasFiltered was true. My change removes wasFiltered in favor of a copy of the state from the most recent unfiltered action, which gets updated every insert, undo, redo, or jump

**Comment by omnidan** [comment]
I published a new version `beta9-3` that should fix this issue (thanks a lot, @davidroeca :tada:)

Let me know if it works now and feel free to reopen if you're still having issues! :grin:
