### ISSUE TITLE
npm install failing on windows

### ISSUE THREAD

**Issue by pl4u** [omnidan/redux-undo#104]
I tried running npm install and the code would not build in Windows 7. It was failing on the "test" target.  "cross-env" needs to be added to the beginning of the line like in the "build:es" target:

"test": "cross-env NODE_ENV=test ./node_modules/.bin/mocha --compilers js:babel-core/register",

**Comment by omnidan** [comment]
@pl4u unfortunately I do not have a windows machine to reproduce this issue on. would you be so kind and see if it works with `cross-env` at the beginning and if it does, open a PR to fix the issue? thanks in advance! :grin:

**Comment by omnidan** [comment]
thanks! merged your PR #105 and published the fix in [`beta9`](https://github.com/omnidan/redux-undo/releases/tag/beta9)
