### ISSUE TITLE
specify action that (re)sets initial state

### ISSUE THREAD

**Issue by FredyC** [omnidan/redux-undo#11]
Regarding talk at #8, it might be better to have an option with the name of action that would always reset history and set initial state. By default it would be @@redux/INIT. This would be completely outside of the filter function.

Thing is that in my case I am loading document from the database and I don't want to allow undo further than that, so I would set this to my LOAD_DOCUMENT_DONE action and when that occurs, history would reset.

**Comment by omnidan** [comment]
Can't this be solved with a custom filter function? If you don't want to use `@@redux/INIT`, just define your own function. Why add a new configuration option for that? Then I'd need to check against two things:

 1. if it matches the specified init action
 2. the filter function

Don't you think solving this with a filter is a cleaner solution? :)

**Comment by FredyC** [comment]
Well, you cannot actually reset the history with the filter function...

**Comment by omnidan** [comment]
@FredyC oh you want it to reset the history with a specific action? I'll adjust the title then :sweat_smile:
