### ISSUE TITLE
Provisions for treating multiple actions as one undo step

### ISSUE THREAD

**Issue by rturnq** [omnidan/redux-undo#115]
I have encountered several use cases where I am dispatching multiple actions that I want to be able to undo as a single step.  Using something like `redux-thunk` quickly exposes the need to handle this scenario.

I have experimented with several approaches to handle this outside of `redux-undo` including middleware and another high-order reducer, but never really found a satisfying answer.  Hacking it directly into `redux-undo` has provided the cleanest implementation.

My approach to the problem is as follows:
- Add a new state property: `suspendCount` which is initially `0`
- Add two new action types: `suspend` and `resume`
  - `suspend` - When dispatched, `redux-undo` increments the `suspendCount` state property.  If `suspendCount` is changing from `0` to `1`, the current state is inserted into the past to provide an undo step.
  - `resume` - When dispatched, `redux-undo` decrements the `suspendCount` state property.  This action also has a payload parameter `revert`.  If`revert` is truthy and `suspendCount` is changing from `1` to `0`, the history is rolled back one step and the current state is discarded.  This is necessary to prevent a redundant undo step if your expected actions were not dispatched or should otherwise be treated as a no-op.
- If `suspendCount` is greater than `0`, state changes will not be added to the history, otherwise the normal rules apply.
- Using a counter instead of a boolean, allows for suspend/resume pairs to be nested while only producing one undo step and without resuming too early.

With this approach I can easily write a middleware to wrap thunks by dispatching `suspend` before executing the thunk then dispatching `resume` afterwards.  It also lets me wrap complex user interactions like drag and drop by dispatching `suspend` in the drag start event and `resume` in the drag end event.

I think this would be a useful addition to this great library.  Would you be receptive to a PR?  Otherwise, if you have another solution I would be interested.

**Comment by peteruithoven** [comment]
Are you sure this is easier than using a filter function? It' very easy to exclude for example the drag actions, which results in only storing the start and stop.
It also enables "debounce", see for example: https://github.com/omnidan/redux-undo/issues/70#issuecomment-200397993

I'm not sure, code architecturally having all the filtering in one place or with the individual action creators is better, both have their benefits.

**Comment by omnidan** [comment]
@rturnq sounds interesting - does this address the bugs #98 and #106? it does sound more complicated than the current solution, but if it ends up fixing all the issues we currently have, it might be worth it :)

**Comment by omnidan** [comment]
@rturnq a PR would be very welcome, then we can see if it ends up fixing any of the bugs we currently have :wink:

**Comment by omnidan** [comment]
closing for now since #139 changed the filtering behaviour, feel free to reopen if this is still an issue with the new version (`beta9-3`).
