### ISSUE TITLE
Why is the state stored internally?

### ISSUE THREAD

**Issue by nickjanssen** [omnidan/redux-undo#120]
From browsing the source code, I noticed that when calling the reducer, the state gets stored internally in `config.history`. Then later, depending on this internal value, a different result gets returned, making the original reducer no longer return the same result even though called with the exact same arguments. I feel this is sort of strange and leads to unpredictable results as shown below. Could anyone explain the rationale behind this design decision?

For example:

```
import test from 'ava'
import expect from 'expect'

import undoable from 'redux-undo'

const reducer = (state = 0, action) => {
  if (action.type === 'INCREMENT') return state + 1
  return state
}

const undoableReducer = undoable(reducer)

test(`undo test 1`, () => {
  let result = undoableReducer(0, { type: 'INCREMENT' })
  expect(result.present).toEqual(1)
})

test(`undo test 2`, () => {
  let result = undoableReducer(0, { type: 'INCREMENT' })
  expect(result.present).toEqual(1)
})
```

In this case, even though exactly the same, the second test will fail:

```
  ✔ redux-undo › undo works 1
  ✖ redux-undo › undo works 2 failed with "Cannot read property 'length' of undefined"
```

Digging deeper, it appears that the second test expects the state to already be in a history object, like this:

```
{
  past: [...pastStatesHere...],
  present: {...currentStateHere...},
  future: [...futureStatesHere...]
}
```

Why doesn't the enhanced reducer simply check if the passed argument is a history object, and create a history object if it's not so it always returns the same result? Thanks in advance, and my apologies if I missed something!

**Comment by omnidan** [comment]
Maybe the naming is a little weird, but this is actually the `initialHistory` (`initialState` wrapped in a history/redux-undo context). It is used to reset the state to the initial values at a later time. We also use this to check if redux-undo has been initialized and do not set that value when the state is still `undefined`.

What you're saying is right though, it is a problem in the current implementation. I think we could use `isHistory` to check if it's been initialized yet and skip initialization when the state is `undefined` to have the same effect. Would you be up for creating a PR with the failing unit tests?

**Comment by pl12133** [comment]
Like @omnidan said, this is a dynamic `initialHistory`. `config.history` is set to a history created from the first valid state put through the `undoable` reducer. This does introduce statefulness which causes the reducer to not be idempotent.

I see no other way to get the `initialHistory` dynamically. We should probably remove this statefulness and promote having the user pass in a `history` with the undoable configuration object if they want to use the `initTypes` actions.

**Comment by omnidan** [comment]
I'll close this for now, feel free to reopen if you can come up with a better solution :grin:

**Comment by davidroeca** [comment]
This may be related to #157. One alternative could be to run the initialization prior to the creation of the wrapped reducer
