### ISSUE TITLE
Feature request: reset wasFiltered

### ISSUE THREAD

**Issue by jscissr** [omnidan/redux-undo#121]
My use case is a point dragged by mouse. The dragging itself is filtered, but on mouseup I want to store the state to the undo stack, even though the mouseup event itself doesn't change the state.
In other words, I propose to add a configuration option like `filter` but with opposite effect, maybe called `resetFilter`, which simply resets `wasFiltered` to `false` when it matches an action, even though that action does not change the `present`.
If the state is an object, there is a workaround to simply clone the state in the reducer for these actions, so that redux-undo thinks the state has changed, but I think this is not really a nice solution.

**Comment by jscissr** [comment]
There is also another problem with the workaround besides that it only works with objects: if the user clicks the point and releases the mouse without moving it, there will be an extraneous entry in the undo log. This wouldn't happen with my proposed feature.

**Comment by pl12133** [comment]
Currently the `wasFiltered` feature is involved in a few bugs, so it is probably not something ready to be iterated on before those bugs are fixed (#98, #106). I would be happy to discuss getting something working for your use case though, it sounds similar to the discussion in #86. There are also ideas in #115 which suggest a more complex way of handling multiple actions.

**Comment by omnidan** [comment]
closing for now since #139 changed the filtering behaviour, feel free to reopen if this is still an issue with the new version.
