### ISSUE TITLE
Is it a good idea to use with redux-persist?

### ISSUE THREAD

**Issue by katopz** [omnidan/redux-undo#122]
Hi guys,

I'm trying to mix `redux-undo` and [`redux-perist`](https://github.com/rt2zz/redux-persist) but I'm not sure it's doable or good idea to do it?

If it's doable where (is the best practice) to hook it? Any hint is welcome.

Thanks

**Comment by pl12133** [comment]
I have not tried it myself, but `redux-persist` looks like it is saving the state of the store. In that case `redux-undo` should be able to handle an `initialState` from `createStore` and will hopefully work fine with that library.

If you try it out please let us know how the two interact?

**Comment by katopz** [comment]
Far as I try, todos filters is working fine but past/present/future from undo history is not rehydrate (even it saved).

BTW, todos only (without undo code) is working fine so some more step need for undo history I think.

Cheers

**Comment by katopz** [comment]
@pl12133 Here's the results which somehow limit with `redux-persist` itself ;/ https://github.com/rt2zz/redux-persist/issues/195 apparently it can't handle/compare nested state value there.

So I come up with simple local storage implement instead [here](https://github.com/katopz/react-todos-with-undo-localstorage) which is working but only `todos` is can be undo/redo, 

`id` and `filters` didn't include in undo/redo and I'm not sure how to deal with it yet (I think `Id` should also decrease when undo or maybe just use todos.length).

Cheers

**Comment by keslert** [comment]
Went through the rigmarole of trying to get this to work today. Here's my solution in case it helps anyone in the future https://gist.github.com/keslert/f0ef5248f2db354968c3c710a4adbe11. In short, it uses redux-persist `transforms` and `stateReconciler` to make the two libraries work together.
