### ISSUE TITLE
Action with undefined type is irregular

### ISSUE THREAD

**Issue by sorrycc** [omnidan/redux-undo#125]
Related code: https://github.com/omnidan/redux-undo/blob/1fa339ad4f231993606764f1253ad64402837ea4/src/reducer.js#L142
- Actions must have a type property that indicates the type of action being performed.
- The undefined type action breaks libraries like redux-actions, https://github.com/acdlite/redux-actions/blob/bea186f/src/handleAction.js#L15

**Comment by pl12133** [comment]
It looks like you are correct, that action `{}` should be changed to `{ type: '' }`.

**Comment by sorrycc** [comment]
I think it's better to use something like `@@REDUX_UNDO/CREATE_HISTORY`, `@@` is conventionally used for internal implementation.

**Comment by afc163** [comment]
+1

**Comment by rroslaniec** [comment]
+1

**Comment by omnidan** [comment]
@sorrycc you're totally right, I just changed this to `@@redux-undo/CREATE_HISTORY` - thanks for the suggestion! :grin:

**Comment by omnidan** [comment]
released `beta9-2` with this change
