### ISSUE TITLE
allow seeking to specific state in history

### ISSUE THREAD

**Issue by FredyC** [omnidan/redux-undo#13]
Just noticed it when messing with debugging. You are passing number of steps to undo/redo functions, but they are not handled in there.

**Comment by omnidan** [comment]
@FredyC I know, I removed this from the README already. When I changed the way the history is stored, I lost the seeking functionality. A solution would be calling `undo`/`redo` multiple times. Do you really think passing a number of steps would be a useful feature though?

**Comment by FredyC** [comment]
Well I can imagine being useful in applications that shows actual history and allow user to move more than one step, but in that case it might more useful to specify some kind of index where you want to move instead of step number. I just noticed it, so you may remove it from the code to avoid confusion.

**Comment by omnidan** [comment]
@FredyC will do that :grin: yeah, seeking could be useful - steps, not so much.

**Comment by omnidan** [comment]
removed steps from the source: https://github.com/omnidan/redux-undo/commit/a7c88bf95816c6c46bde0fec1b81215edd97c9fc
