### ISSUE TITLE
about mapDispatchToprops

### ISSUE THREAD

**Issue by a360305993** [omnidan/redux-undo#132]
i saw examples at http://redux.js.org/docs/introduction/Examples.html    .Todos with Undo

i am very confused that i only change one place,and then it doesn't work!

the old one is
 https://github.com/reactjs/redux/blob/master/examples/todos-with-undo/src/containers/UndoRedo.js

before change:
const mapDispatchToProps = ({
  onUndo: UndoActionCreators.undo,
  onRedo: UndoActionCreators.redo
})

after change:
const mapDispatchToProps = ()=>({
  onUndo: UndoActionCreators.undo,
  onRedo: UndoActionCreators.redo
})
 i changed mapDispatchToProps form a objcet to a function.and doesn't work;
but from redux's doc,mapDispatchToProps  is a function.
Am I used it wrong?Thanks a lot.

**Comment by omnidan** [comment]
If you look at the [Usage with React](http://redux.js.org/docs/basics/UsageWithReact.html) section in the redux docs, you will see that you manually need to wrap your action creators with `dispatch` if you use a function, e.g.:

```js
const mapDispatchToProps = (dispatch) => ({
  onUndo: dispatch(UndoActionCreators.undo),
  onRedo: dispatch(UndoActionCreators.redo)
})
```

You can also use the [bindActionCreators](http://redux.js.org/docs/api/bindActionCreators.html) helper function to accomplish this:

```js
const mapDispatchToProps = (dispatch) =>
  bindActionCreators({
    onUndo: UndoActionCreators.undo,
    onRedo: UndoActionCreators.redo
  }, dispatch)
```

**Comment by a360305993** [comment]
Sorry to bother you.I am a beginer of redux.Next time I will think twice before asking a question.Thanks again.

**Comment by omnidan** [comment]
@a360305993 it's alright :grin: you might want to ask these questions on stackoverflow or [gitter](https://gitter.im/omnidan/redux-undo), though, because they're not really issues related to redux-undo :wink:

**Comment by a360305993** [comment]
😁 got it. 😁i just forget my password of stackoverflow.So I come here.and I have recovery my account right now.😁

**Comment by omnidan** [comment]
@a360305993 feel free to ask me directly on [gitter](https://gitter.im/omnidan/redux-undo) :wink:

**Comment by a360305993** [comment]
@omnidan .ok, thakns!
