### ISSUE TITLE
Can I use redux-undo@beta for production project ?

### ISSUE THREAD

**Issue by NicolasAndersen** [omnidan/redux-undo#136]
Hi Omnidan,
redux-undo is very wonderful. Can I use redux-undo@beta  for a production project? Is there any problem with redux-undo@beta .

Thank you.

Nicolas

**Comment by omnidan** [comment]
@NicolasAndersen yes, you can use beta for a production project - it's stable, however, there are still a few issues with the `filter` functionality, which is why there is no 1.0 release yet.
