### ISSUE TITLE
 How to use redux-undo with redux-actions

### ISSUE THREAD

**Issue by janryWang** [omnidan/redux-undo#137]

**Comment by omnidan** [comment]
@janryWang can you give us a bit more information - What have you tried? What did you expect to happen? What happened? Any problems/issues/errors? How to reproduce the issue? (Maybe even with a small example)

Thanks in advance :wink:

**Comment by janryWang** [comment]
when i use the redux-undo@beta-9 , it worked,but when i use the redux-undo@0.6.x , it was not worked
