### ISSUE TITLE
COMPLETE_TODO - doesn't re-render after UNDO

### ISSUE THREAD

**Issue by thomasyates** [omnidan/redux-undo#14]
This seemed like the best place to raise an issue with the example in redux: https://github.com/rackt/redux/tree/master/examples/todos-with-undo. 

Undo / redo works as expected for adding a Todo, but doesn't seem to work with the COMPLETE_TODO action. 
![test](https://cloud.githubusercontent.com/assets/9977923/10107636/638afffe-63b4-11e5-8b7e-bf05d258cb94.gif)
Any ideas?

**Comment by omnidan** [comment]
@thomasyates thanks for reporting this issue! yes, this is the right place :sweat_smile: 

I just tested it and it seems to work fine for me :o 

Can you please check your `redux` and `redux-undo` versions? Maybe make sure nothing in the code was changed - do a fresh clone, maybe?

**Comment by thomasyates** [comment]
The issue was with [Object.assign()](https://github.com/rackt/redux/blob/master/examples/todos-with-undo/reducers.js#L28) in reducers.js, which isn't working even with a fresh install and clone.
`Uncaught TypeError: Object.assign is not a function`
But works fine after installing babel-runtime. So I guess something's up with the babel config?
``` javascript
{
  test: /\.js?$/,
  exclude: /node_modules/,
  loaders: ['babel?optional=runtime']
}
```

**Comment by omnidan** [comment]
@thomasyates all I did was clone it, run `npm install` and `npm start`. I might have some parts of babel installed globally though (because I have the `babel` command available).

`Object.assign is not a function` sounds like you're not running on ES6 - so yeah, seems like a babel issue.

Does adding `?optional=runtime` solve the issue for you? I copied the config from the `todomvc` example, so that would have (had) the same issue for you, as it uses `Object.assign` too.

**Comment by omnidan** [comment]
@thomasyates I'll close this issue here, you should open it on the `redux` issue tracker instead and link to it there as it has nothing to do with `redux-undo`.

**Comment by thomasyates** [comment]
Cheers for the speedy responses, Dan. I've upgrade babel globally and the issue has gone away. Keep up the good work :+1:

**Comment by omnidan** [comment]
@thomasyates Thanks! Alright, I just hope it works if you don't have babel installed at all, I'll have to test it in a VM or something.

**Comment by omnidan** [comment]
Works fine in a VM (fresh installation without babel) :ok_hand:
