### ISSUE TITLE
Can I use immutable with this project? 

### ISSUE THREAD

**Issue by yoohan-dex** [omnidan/redux-undo#140]

**Comment by davidroeca** [comment]
I've had trouble with the npm release overloading the call stack, so I'd recommend using a beta version. In theory it should work, though the past and future have to be plain arrays and the top level is a plain object for now until the code base is abstracted further.

if you're having trouble with the beta, also try adding https://github.com/omnidan/redux-undo/pull/139 as a git dependency (unless it gets merged). I wrote the changes and am currently using an immutable map as my present state object in the project I use it for

**Comment by omnidan** [comment]
#139 got merged and published now (`beta9-3`), so this should work fine. If it doesn't, feel free to reopen this issue. 😃

**Comment by wootencl** [comment]
@davidroeca  Can you give an example of how you've changed `present` from a vanilla object to an immutable JS Map?

**Comment by davidroeca** [comment]
@wootencl yep, sounds about right--had that same issue in my project. I think I wrote a selector to get the present so that the funky vanilla-js to immutable stuff was encapsulated in one function

**Comment by wootencl** [comment]
haha, yup. Exactly what I did. Selector for those that stumble upon this issue:
```
const undoableStateSelect = (state, path = []) => 
  state.get(UNDOABLE_STATE_KEY)[PRESENT].getIn([...path])
```
