### ISSUE TITLE
Making sure reducers gets called only once when multiple reducers available

### ISSUE THREAD

**Issue by tomaswitek** [omnidan/redux-undo#142]
Hi @omnidan first of all thanks for your contribution 😏 

I have a similar question to https://github.com/omnidan/redux-undo/issues/77 and https://github.com/omnidan/redux-undo/issues/84.

Can I somehow make sure to call undoable reducer only on desired state container?

Lets assume I have a following state:

```
combineReducers({
  todos: undoable(todos),
  users: undoable(users)
});
```

If I do state changes to both containers(todos and users) and than I call `undo` both state containers will be reverted because `undo` reducer gets called twice.

Do I have to start to play with `UNDO_TODO` and `UNDO_USER` actions or is there an another way to achieve my goal?

Thx for you time

**Comment by omnidan** [comment]
Yes, you need to specify custom undo actions for the sub-reducers, e.g.

```
combineReducers({
  todos: undoable(todos, { undoType: 'UNDO_TODO' }),
  users: undoable(users, { undoType: 'UNDO_USER' })
})
```

**Comment by tomaswitek** [comment]
Ohh I see: https://github.com/omnidan/redux-undo/blob/master/src/reducer.js#L151
Thx man
