### ISSUE TITLE
Support slice reducers

### ISSUE THREAD

**Issue by mauron85** [omnidan/redux-undo#147]
Some reducers need to access state from different slice of state as written in
http://redux.js.org/docs/recipes/reducers/BeyondCombineReducers.html#sharing-data-between-slice-reducers

Example

```
const undoableDeliveriesReducer = undoable(deliveriesReducer);
const undoableRoutesReducer = undoable(routesReducer)

export default function entitiesReducer(state = defaultState, action) {
  return {
    couriers: couriersReducer(state.couriers, action),
    deliveries: undoableDeliveriesReducer(state.deliveries, action),
    routes: undoableRoutesReducer(state.routes, action, state.deliveries),
  };
}
```

Currently undoable only pass state and action to actual reducers, so in case of `routesReducer` `state.deliveries` will be null. Fix should be easy.

**Comment by davidroeca** [comment]
Hi @mauron85 I just made a pull request for this issue

**Comment by mauron85** [comment]
Nice. In meantime I realised that redux-undo is not suitable for my use case as I need to undo actions, not just revert state of the UI.

**Comment by davidroeca** [comment]
@mauron85 what's the difference in that case? If your reducer is undoable, then the state changes associated with the action will be undone. The action will be undone, no?

If you're referring to thunk actions (actions that have side-effects that result in more actions), you can look into filtering.

**Comment by mauron85** [comment]
I also need to undo action on the server, but I cannot determine which action it was from state change.

**Comment by davidroeca** [comment]
I see, so not a redux action but an API call. Yeah, undoing side effects outside the redux store is outside the scope of this library. I assume there would have to be specific logic for each back-end call to undo the call. Though in either case I don't think there would be a simple way to undo a deletion

**Comment by mauron85** [comment]
Yes,  https://github.com/powtoon/redux-undo-redo seems is doing it by custom middleware and revertingActions. Anyway for state/UI only undos, your module is perfect.

**Comment by davidroeca** [comment]
Ah interesting, definitely provides a backend-compatible solution at the cost of usability. I'm thinking this sort of functionality could be incorporated into this library as a config option. I'll look into it when I have the time

**Comment by davidroeca** [comment]
Created a new issue (https://github.com/omnidan/redux-undo/issues/150) and closing this one since the PR has been merged
