### ISSUE TITLE
When is next stable released?

### ISSUE THREAD

**Issue by peteruithoven** [omnidan/redux-undo#148]
So the project has been in beta for quite a while, fixing some big issues, but now I'm curious when we'll see the next stable major version? Is there something that's blocking this release? For example [Create guide to switch from 0.x to 1.0-beta](https://github.com/omnidan/redux-undo/issues/73)?

**Comment by acateland** [comment]
@omnidan do you need help moving this lib toward the next stable version ?

**Comment by omnidan** [comment]
@peteruithoven @acateland actually, the main issue is lack of time on my side. 😞  I have a lot of other projects right now (my startup, writing my bachelor thesis and a book). Any help would be very appreciated! I will still be able to review PRs and respond to comments here though, don't worry :wink:

**Comment by omnidan** [comment]
I am also almost always available [on gitter](https://gitter.im/omnidan/redux-undo) if you want to have a discussion about something 😄

**Comment by omnidan** [comment]
_from #197:_

there are a lot of things that need to be worked on, like async actions, performance problems, etc. The main issue is that I do not have time or motivation for this project anymore (I do not use it myself at the moment) and nobody else is actively maintaining it right now.

If anyone would be interested in helping maintain the library, that would be awesome. just hop on gitter and we can discuss the future of the library together there: https://gitter.im/omnidan/redux-undo

**Comment by nmay231** [comment]
1.0 released!

#251
