### ISSUE TITLE
`clearHistoryType` and `initTypes` question.

### ISSUE THREAD

**Issue by acateland** [omnidan/redux-undo#152]
Hello,

Why not give the possibilities to let the `clearHistoryType` and `initTypes` action to flow trought the wrapped reducer ?

**Comment by omnidan** [comment]
@acateland Sounds interesting. Do you have any possible use cases for this? I think we should always first think about use cases before adding more configuration/complexity.

**Comment by acateland** [comment]
well i have one example maybe contrieved one but.

I work a on graph tool where i use a higher order reducer to populate some placholder nodes.
And i want to on the same action, reinit history wrapped redux mountpoint, and repopulate it.
Why ?
Because if i do not, the higher order reducer will temporary populate with placeholder creating a new entry on the history wich i do not want.

**Comment by peteruithoven** [comment]
I might not understand your usecase, but couldn't you handle this with the `neverSkipReducer` config?

**Comment by nmay231** [comment]
As @peteruithoven mentioned, the best way to do this is to pass `neverSkipReducer: true` to the config and handle the re-init manually in the wrapped reducer.
