### ISSUE TITLE
Initial state is not stored into "past" array

### ISSUE THREAD

**Issue by rsaladocid** [omnidan/redux-undo#157]
I have a question, why is the initial state not stored into "past" array? Currently, it is impossible return to the initial state by means of "undo" action because of this reason.

**Comment by davidroeca** [comment]
If you're not filtering anything, this problem likely doesn't exist. The initial state will be stored in the past after the first action changes the state. Filtering potentially changes this behavior, since redux-undo does not track filtered changes, so the state immediately before the first state-changing action will be saved in that case.

The way around this is to fire an unfiltered state-changing action immediately after initialization, so that the initial state is saved.

**Comment by rsaladocid** [comment]
Yes, I am filtering some actions, but the state immediately before the first state-changing action is lost. The state is initialized after the first non-filtered action is performed (so the initial state is not stored)

**Comment by davidroeca** [comment]
Please provide a simple breaking example where this happens

**Comment by sidonaldson** [comment]
@rsaladocid did you get anywhere with this? I've just stumbled into the same issue. 

I've setup my store and everything works except the pre-loaded first state is lost on first update. I'll try and leave a little sample code if it'll help.

```
const store = configureStore({
		thingState: {
			present: {...initialState},
			future: [],
			past: []
		}
	});
```

```
export default combineReducers({
	thingState: Undoable(Thing, {limit: 20})
});
```

```
function updateState(state = initialState, action) {
	switch (action.type) {

		case 'UPDATED':
			let newValues = {
				test: 'test'
			};
        	return {...state, ...newValues};

		default:
			return state;
	}
}
```

I can log all the way through the process and the data is being updated correct (and isn't the same for example)

**Comment by sidonaldson** [comment]
Ah, found it. Redux Undo seems to know what to do, the mistake was to try to populate the initial state as a child object. Instead just add the object.

```
const store = configureStore({
    present: initialState,
    future: [],
    past: []	
});```

**Comment by sidonaldson** [comment]
@davidroeca would you be able to offer any advice on the above? I can't seem to make any headway solving it

**Comment by sidonaldson** [comment]
Ah!
Stumbled across this [SO post](https://stackoverflow.com/questions/43400369/initializing-history-for-redux-undo-isnt-populating-past-or-future) and the poster solved it by rolling back versions. I too rolled back to beta 7 and it now works as expected. 
I think there is a bug somewhere but I'm afraid my knowledge isn't strong enough to suggest where it may lie.

**Comment by davidroeca** [comment]
Have you tried setting syncFilter: true in your config? There's weird
behavior if you filter some of the first actions at the start of your app,
since filtered actions by default now mutate state but don't get undone.
syncFilter fixes this but the user will have to undo extra times if you're
filtering downstream actions from thunks, just as they would in beta-7

**Comment by sidonaldson** [comment]
@davidroeca I'm not filtering at all. Completely stock set-up in that I wrap my reducer and then feed it some initial state.

**Comment by davidroeca** [comment]
Strange, not sure what caused this--there have been a decent number of changes since beta7. So to confirm, none of the debug messages in the block at https://github.com/omnidan/redux-undo/blob/master/src/reducer.js#L177 are recorded?

**Comment by sidonaldson** [comment]
@davidroeca correct. The image in this [answer](https://github.com/omnidan/redux-undo/issues/157#issuecomment-310029893) shows the first debug message and that is after the first action is called. Nothing before that.

**Comment by davidroeca** [comment]
Alright I'm still not sure where the issue is. Please break the following example or let me know what's wrong with the behavior: 

```bash
git clone https://github.com/davidroeca/redux-undo.git
cd redux-undo
git checkout preloaded
cd examples/preloaded
npm install
npm run build
npm run start
```
Go to `http://localhost:8080` on a browser with the redux devtools extension (or just check the debug messages)

**Comment by sidonaldson** [comment]
@davidroeca yup. that's exactly it. I'm relieved you recreated it with such a basic initial state as well, was worried my complex state object was to blame.

**Comment by omnidan** [comment]
published `beta9-9-5` with this fix, let me know if it works /cc @sidonaldson @davidroeca

**Comment by sidonaldson** [comment]
@omnidan @davidroeca confirmed as fixed in the test project above and in my own current production app. Thanks for resolving!
