### ISSUE TITLE
Rename `ifAction` to `includeAction`

### ISSUE THREAD

**Issue by ianobermiller** [omnidan/redux-undo#16]
Rename `ifAction` to `includeAction` to better complement `excludeAction`. Also I always find the term "filter" to be confusing, so "filter include action" is more clear to me than "filter if action". 

Of course filter in JS means keep the things that match the predicate, but I still think `include` is more clear.

**Comment by omnidan** [comment]
@ianobermiller you're totally right. I'll get this into 0.5

**Comment by FredyC** [comment]
:+1:
