### ISSUE TITLE
Get  Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by MBehtemam** [omnidan/redux-undo#163]
i try to implement redux-undo to my app so my reducers is like 

` const combine = combineReducers({
    designer,
    activities:undoable(activities),
    activitySelectedIndex,
    activitySelectedId,
    activityTypes,
    componentSelectedIndex,
    router: routerReducer
})
`

and also : 

`function mapDispachToProps(dispatch){
     return bindActionCreators(Object.assign({},actionCreators,UndoActionCreators), dispatch);
}`

but i get this error : 
`Uncaught TypeError: Cannot read property 'length' of undefined
    at lengthWithoutFuture (reducer.js:25)
    at insert (reducer.js:33)
    at reducer.js:307
    at combination (combineReducers.js:132)
    at dispatch (createStore.js:179)
    at createStore (createStore.js:253)
    at applyMiddleware.js:38
    at createStore (createStore.js:65)
    at Object.<anonymous> (Routes.js:27)
    at __webpack_require__ (bootstrap df649ed…:555)`

**Comment by davidroeca** [comment]
Hi @MBehtemam, thanks for the issue! Still not sure where the bug is--which version are you on, and what does the state default to in the `activities` reducer (prior to wrapping with undoable)?

**Comment by MBehtemam** [comment]
Hi , my redux-undo version in package.json is `    "redux-undo": "^1.0.0-beta9-9"` and my activities is nested object 
`  "activities":[
        {
        "id":1,
        "type":{"name":"Form","value":"form"},
        "title":"Videos",
        "titlebar":"Some titlebar",
        "get":[],
        "action":[],
        "call":[],
        "components":[]
            }
    ]`

activity is an array with object , each object contain id,type,title,titlebar, get,action,call,components, get and call and components is also array and type is an object , and activity reducer contains action for adding and removing componnets and action and ect.

**Comment by davidroeca** [comment]
In the `activities` reducer, what does your function signature look like? Below are two scenarios I'm thinking you might have:

*Scenario 1*
```js
const activities = (state, action) => ...
```

*Scenario 2*
```js
const activities = (state = [], action) => ...
```

Or something different?

The functionality of `undoable` is slightly different in these two scenarios and will help pinpoint the bug. If you have one, try the other and see if it works and let me know which one is broken.

If these errors are happening in the browser (and compilation finishes), try to set the `debug: true` flag and see what `console.log` outputs:
```js
const combine = combineReducers({ designer, activities:undoable(activities, {debug: true}), activitySelectedIndex, activitySelectedId, activityTypes, componentSelectedIndex, router: routerReducer })
```

**Comment by MBehtemam** [comment]
my activities reducer signature is : 

`function activitiesReducer(state = {}, action) {}`

**Comment by davidroeca** [comment]
I haven't been able to reproduce this issue, so it's likely dependencies not working together nicely. Does your project compile without `undoable`? What sorts of middleware are you using? Does `undoable` work without some of the middleware?

**Comment by omnidan** [comment]
@MBehtemam it would be very helpful if you could put up a small project on github that reproduces this issue - so that we can simply clone it and see what's wrong :grin:

**Comment by jcperez-ch** [comment]
@MBehtemam since activities is an array, you probably want to default the initialState as an array, like:

```js
function activitiesReducer(state = [], action) {}
```

Right?
Also do you use an initialState when you create your store that could propagate the initial state of the activities subtree that doesn't contain the `past` array?

**Comment by joelzimmer** [comment]
I'm seeing the same issue, where I have a reducer that looks like:

```js
export default (state = {}, action) => {
   ...
}```

The first time the application loads, the history is successfully created in the format:
```js
{
   past: [],
   present: myState,
   future: [],
}
```

The second time the application loads, the state looks like:
```js
mystate
```
which doesn't have a `past` key, causing the `insert` to fail.

**Comment by hamdiwanis** [comment]
it's because the reducer you pass to the undoable function only gets the present state, but you can access the full state outside it normally :)

`
default:
        res = reducer(
          history.present,
          action,
          ...slices
        )
`

**Comment by joelzimmer** [comment]
@hamdiwanis just so i'm clear - that'd be the `default` response in the `reducer` being wrapped? Just want to make sure I have full context on what you are saying.

**Comment by hamdiwanis** [comment]
@joelzimmer yes, that's what I got from reading the code base :)

**Comment by davidroeca** [comment]
@joelzimmer I'm assuming that your application still has the reducer in memory from the previous run.

Check out https://github.com/omnidan/redux-undo/blob/0d93dd544cf25ba5eaa490a4c406f7e148aba988/src/reducer.js#L120 which is likely what's causing this behavior.

The bottom line here is that once the reducer has "initialized" the state once, it will only accept the expected history format.

Would an export of something like [newHistory](https://github.com/omnidan/redux-undo/blob/0d93dd544cf25ba5eaa490a4c406f7e148aba988/src/reducer.js#L5) or [createHistory](https://github.com/omnidan/redux-undo/blob/0d93dd544cf25ba5eaa490a4c406f7e148aba988/src/reducer.js#L18) be helpful so that you can be in sync with the library's history format on future runs? Not sure what's going on in your application, since the applications I've written with library typically recreate the reducer (and thus reinitialize it) on every run

**Comment by joelzimmer** [comment]
@davidroeca I think exporting those functions would be incredibly helpful.

**Comment by omnidan** [comment]
@joelzimmer released `beta9-9-7` with the `newHistory` function, let me know if that solves your issue

**Comment by joelzimmer** [comment]
@omnidan Thanks! I ended up fixing it through this conversation on [gitter](https://gitter.im/omnidan/redux-undo?at=59b191594e50cfde27153ae7): 
> i figured it out - was attempting to create the undoable reducer on my server, but needed to create it on the client, which seems to have solved it.

So I don't know if it was code based, maybe just config based.

**Comment by mkalygin** [comment]
I can confirm that one of the possible reasons of this error can be SSR. It also happens to me on the 2nd and subsequent renders only.

**Comment by mkalygin** [comment]
For anyone in the future who face with this problem with SSR and hydration, here is a little workaround, which mimics `undoable` for the server bundle:

```
import clientUndoable from 'redux-undo';

const serverUndoable = reducer => (state = defaultState, action = {}, ...slices) => ({
  past: [],
  present: reducer(state.present || state, action, ...slices),
  future: [],
});

const undoable = reducer => (
  IS_SERVER_RENDERING ? serverUndoable(reducer) : clientUndoable(reducer)
);
```

**Comment by TeaBough** [comment]
I've had the same problem with jest in a test suite, thus I've used this mock :

```
jest.mock('redux-undo', () => ({
  __esModule: true,
  default: reducer => (state = {}, action = {}, ...slices) => ({
    past: [],
    present: reducer(state.present || state, action, ...slices),
    future: [],
  }),
  excludeAction: () => {},
}));
```

**Comment by arthurodriguesbatista** [comment]
@TeaBough can you show me a functional version of redux-undo with jest?

**Comment by TeaBough** [comment]
> 

Sorry I'm not using redux-undo anymore ...
