### ISSUE TITLE
Deep copy of states

### ISSUE THREAD

**Issue by johnguerson** [omnidan/redux-undo#166]
Hello guys, 

Is copy of present, past, latestUnfiltered, future, shallow? I mean, do they consider a complex object with multiple arrays of other objects? Histories shouldn't point between each other objects right? Is that something you guys would do in a near future?

I have a complext state object like that and am wonder if I'll have to implement my own undo/redo... I tried redux-undo but seem copies are shallow for some reason. Maybe there is something else wrong on my reducers too, but basically all I am doing is

```
undoable(myReducer,
  debug:true,
  synFilter: true,
  filter: includeAction([Action.MY_ACTION])
);
```

I noticed if I kept syncFilter false my past state wasn't updated correctly. myReducer have a bunch of other actions I didn't want to be undoable/redoable. Only MY_ACTION and a few other should.

You guys are doing an awesome work and thanks a lot in advance for any feedback,
John,

**Comment by davidroeca** [comment]
Hi John,

The references are shallow when it makes sense. `_latestUnfiltered` and `present` have the same reference when they're in sync (and thus meet the === equality check).

As for deep copies of each state, that should be a question of how your own reducer is implemented. Using a library such as [immutablejs](https://facebook.github.io/immutable-js/docs/#/) will help. If you're using vanilla js, use `Object.assign({}, state, {...updated values...})` to avoid this issue.

If this doesn't help, please elaborate with your concerns here

Thanks,
David

**Comment by davidroeca** [comment]
Closing, since deep/shallow references should be managed by the wrapped reducer
