### ISSUE TITLE
Does redux-undo work when preloading initialState with createstore?

### ISSUE THREAD

**Issue by AlessandroDM** [omnidan/redux-undo#168]
Hello,
First of all thanks for the library.
Then, I am not sure if I am making a mistake somewhere but whenever I try to pre-load the state using the createStore function the "present" state is undefined.

Assigning the state directly on the reducer works without issues.

To replicate the problem just remove the default value of the state of the reducer and create an initial state const and pass it on the createStore as parameter (like in the todo example).

Is there anything that needs to be done to make sure preloaded states work?
Any input would be appreciated.

**Comment by sidonaldson** [comment]
I don't know if this will help but this is how I set-up my reducer and it works with default values in the reducer declaration.

```
const store = configureStore({
    myState: {
        present: [{...defaultValues}],
        future: [],
        past: []
    }
});
```

**Comment by AlessandroDM** [comment]
Hello sidonaldson,
ahhh... indeed..  basically to preload the store you need to add the present, future and past (and load in present the values)...

I my initial tests I was adding a default value in the reducer directly and the "present / future / history" were already there so I thought I did not have to manually do them in the createStore function...

Thanks for the help, after I moved my default variables inside the "present" object it works.

**Comment by sidonaldson** [comment]
@AlessandroDM glad to help!
