### ISSUE TITLE
Simplify API

### ISSUE THREAD

**Issue by omnidan** [omnidan/redux-undo#17]
I want to change this:

```js
{
  present: {...currentStateHere...},
  history: {
    past: [...pastStatesHere...],
    present: {...currentStateHere...},
    future: [...futureStatesHere...]
  }
}
```

to be more like this:

```js
{
  past: [...pastStatesHere...],
  present: {...currentStateHere...},
  future: [...futureStatesHere...]
}
```

`.history` could be a reference to `this`, so doing `state.history.present` still works and this is not a breaking change :metal:

**Comment by FredyC** [comment]
Definitely good idea, go for it :+1: 

It's bit breaking change thou for the spot where I am asking for the size of history, eg. `state.data.history.past.length > 0`

**Comment by omnidan** [comment]
@FredyC nope! it's not a breaking change, `state.data.history.past.length > 0` will still work fine. I even tested it with the [`todos-with-undo` example](https://github.com/rackt/redux/tree/master/examples/todos-with-undo) as well as [my boilerplate](https://github.com/omnidan/redux-undo-boilerplate).

It's not a fancy solution, but it works. I tried making it a getter so I can display a deprecation warning, but then `combineReducers` calls every key in the state, so it also calls `.history`, which triggers the deprecation warnings.

Anyway, everyone really should switch to the new, simple api as I'll remove the reference to `history` in a future version.
