### ISSUE TITLE
Filtered action should not affect grouping

### ISSUE THREAD

**Issue by xargi** [omnidan/redux-undo#171]
Ran into this one while trying to implement a distinct state filter for immutable.

I have a groupBy function that groups actions based on a debounced incrementing identifier. I also have a filter that filters out state transitions where the immutable state does not change (because of fromJS, simple reference equality used by the library does not work). Unfortunately every time a state transition is filtered out by the distinct state filter, the group also gets reset causing extraneous states to be pushed into the history.

**Comment by davidroeca** [comment]
Just added the fix for this in my PR. I realize the unfiltered group wasn't passed to the filtered state, which was the problem

**Comment by xargi** [comment]
Somewhat related to this, I don't think the built in distinct state filter should make the comparison ```history.present === res``` but rather compare the latest unfiltered state to res, because while the state didn't change from the app's perspective, it can change from undoable's perspective. For two consecutive actions, the first one can be filtered but the second one not and in that case the latest unfiltered state should still get recorded into the history.

**Comment by davidroeca** [comment]
Closing this since the initial request was handled by #167. See #173 for the new issue

**Comment by omnidan** [comment]
published `9-9-6` with this fix, let me know if it works!
