### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by mblout** [omnidan/redux-undo#172]
with the latest redux-undo@1.0.0-beta9-9-3, I'm seeing this error:
Uncaught SyntaxError: Unexpected token export
  at node_modules/redux-undo/dist/redux-undo.js:64

redux-undo@1.0.0-beta9-9-1 does not have this issue

**Comment by omnidan** [comment]
@mblout can you offer a small example where this doesn't work? what node version etc are you using?

I just tried using 9-9-3 with the todos-with-undo example and it works fine.

Could have been broken by #165 or #167

**Comment by mblout** [comment]
I am loading an app in Chrome.. I'm trying to figure out how to quickly modify the 'todos-with-undo' example to load the dist/redux-undo.js instead of the libs/, but I'm not familiar enough with the webpack middleware (yet). will keep trying.

**Comment by mblout** [comment]
it happens when using requirejs to load dist/redux-undo.js.  hacked 'todos-with-undo' to use grunt-connect and requirejs.  you should be able to unzip, 'npm install', 'grunt', and load localhost:1377/index2.html to see the error (I hope, if I packaged this up correctly).

[todos-with-undo-require.zip](https://github.com/omnidan/redux-undo/files/1127912/todos-with-undo-require.zip)

**Comment by davidroeca** [comment]
My guess is that this comes from the update to webpack 2 or babel. I assume it's building closer to es6--I don't have the time to look into the configuration changes but this might be a step in the right direction https://github.com/59naga/babel-plugin-add-module-exports

**Comment by omnidan** [comment]
thanks for the example @mblout and thanks for the hint @davidroeca :grin:

I built it with the babel plugin and the example didn't error anymore.

released `beta9-9-4` with a fix, let me know if it works!

**Comment by mblout** [comment]
pulled beta9-9-4, and looks good here, thanks!
