### ISSUE TITLE
Compare distinct states with _latestUnfiltered rather than present

### ISSUE THREAD

**Issue by davidroeca** [omnidan/redux-undo#173]
Mentioned in #171 by @xargi

The thought is that filtered state might invalidate unfiltered actions that yield the same current state, which prevents it from being recorded in the history.

The fix: change `history.present === res` to `history._latestUnfiltered === res`

**Comment by omnidan** [comment]
published `9-9-6` with this fix, let me know if it works!

**Comment by welkup** [comment]
Works as expected. Thanks so much!
