### ISSUE TITLE
Is the 'redux' dependency necessary?

### ISSUE THREAD

**Issue by alexjlockwood** [omnidan/redux-undo#175]
The `package.json` file lists `redux` as a dependency. Is it possible for it to be removed? It seems like it is not being used by this library, and redux depends on some heavy-ish things like lodash.

I am using redux-undo right now with `@ngrx/store` with Angular, so in my case I don't need to depend on `redux`.

**Comment by omnidan** [comment]
nice catch! you are right - it is only required for the tests, so I added `redux` to the `devDependencies` instead.

**Comment by omnidan** [comment]
published `beta9-9-5` with this change
