### ISSUE TITLE
Make it possible to return 'undefined' from a custom groupBy function

### ISSUE THREAD

**Issue by alexjlockwood** [omnidan/redux-undo#178]
Right now you need to return 'null' to the groupBy function. I have a lint rule that forbids using `null`, so it would be nice if it would also accept `undefined` as well.

Feel free to ignore if this would be a breaking change. :)

**Comment by davidroeca** [comment]
Have you tried using `undefined`? The group comparison uses the `== null` check (rather than `=== null`) so I think this should work already

**Comment by alexjlockwood** [comment]
Oh! Right! I totally forgot about that. Sorry I'm a javascript newbie. :D
