### ISSUE TITLE
one a reducer's state value which has deep structure is stored in the past array. it is changed meantime when present state is changed.

### ISSUE THREAD

**Issue by vicky8989** [omnidan/redux-undo#180]
i find an issue with this plugin.
when a reducer value has deep structure,the past's value is changed by the present value.this lead to that the states are all the same when undo/redo action is already dispatched. For example:
one state structure is like below:
const initialState = {
        value1:true,
        value2: 'value',
        needDeepCopy:{
            test:'1',
            arr:[1,2,3]
        }
}

operate: when the state is changed to like below:
const initialState = {
        value1:false,           //changed present
        value2: 'value',
        needDeepCopy:{
            test:'1',
            arr:[4,5,6]      //changed present
        }
}

 when using the redux-undo plugin,the exact result i think is like below:
past:[ {
        value1:true,
        value2: 'value',
        needDeepCopy:{
            test:'1',
            arr:[1,2,3]
        }
}]
present:[ {
        value1:false,
        value2: 'value',
        needDeepCopy:{
            test:'1',
            arr:[4,5,6]
        }
}]

but the actual result is like below:

past:[ {
        value1:true,
        value2: 'value',
        needDeepCopy:{
            test:'1',
            arr:[1,2,3]
        }
}]
present:[ {
        value1:false,  //right
        value2: 'value',
        needDeepCopy:{
            test:'1',
            arr:[1,2,3]         //wrong
        }
}]

It's like that the past value and the present value has an reference relationship. Did anyone has the same question like me ?  and did anyone resolve this problem? i will appreciate it if any answers.

**Comment by davidroeca** [comment]
This library assumes that elements of your state object are not mutated, as is common practice in redux. Make sure you're returning new objects with your reducers. `Object.assign` and the object spread operator are a few ways of doing this. See https://github.com/omnidan/redux-undo/issues/166 for some related discussion.

**Comment by vicky8989** [comment]
Thanks for your answer @davidroeca . I have seen the issue #166 , i will try to solve the issue by immutable.js or vanilla js. I am debugging this issue for three days. Hope it will work. Thanks a lot.

**Comment by omnidan** [comment]
@vicky8989 you do not need to use immutable.js to do immutable updates with Redux (but feel free to do so if you like it!)

Have a look at [the Redux documentation page on immutable update patterns](http://redux.js.org/docs/recipes/reducers/ImmutableUpdatePatterns.html) for more information on how to solve these kinds of issues.

If anything else is unclear or there is another issue, feel free to reopen this :grin:
