### ISSUE TITLE
Build error related to babel

### ISSUE THREAD

**Issue by beornborn** [omnidan/redux-undo#182]
v0.6.0 

`error: bundling failed: "TransformError: [app_folder]/node_modules/redux-undo/lib/index.js: [BABEL] [app_folder]/node_modules/redux-undo/lib/index.js: Using removed Babel 5 option: [app_folder]/node_modules/redux-undo/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets"`

v0.6.1

`error: bundling failed: "TransformError: [app_folder]/node_modules/redux-undo/lib/index.js: Couldn't find preset \"es2015\" relative to directory \"[app_folder]/node_modules/redux-undo\""`

v1.0.0-beta9-9-6

`error: bundling failed: "TransformError: [app]/node_modules/redux-undo/lib/index.js: Unknown plugin \"add-module-exports\" specified in \"[app]/node_modules/redux-undo/.babelrc\" at 0, attempted to resolve relative to \"[app]/node_modules/redux-undo\""`

**Comment by omnidan** [comment]
@beornborn is this only an issue in 0.x or also with the beta release?

**Comment by beornborn** [comment]
@omnidan updated description

**Comment by omnidan** [comment]
@beornborn alright, that is very weird - can you provide a small example repo that reproduces this error?

**Comment by davidroeca** [comment]
@bernborn which version of babel are you using in your project? Which npm version are you using (or are you using something different like yarn)? Also try installing `babel-plugin-add-module-exports` as a dependency in your project and let us know if that works as a temporary fix

**Comment by beornborn** [comment]
@omnidan @davidroeca 
1 detail that can be important is that I am using react-native 0.46.4
The error happens on `import undoable from 'redux-undo'` so it should be easy to reproduce (I'll create example repo when find a minute)
yarn 0.24.6

**Comment by tyeon95** [comment]
Any update on this? I am getting the same error at `import undoable from 'redux-undo'`

**Comment by davidroeca** [comment]
@tyeon95 are you using `react-native` or something else?

@beornborn any update on the example repo?

I haven't been able to reproduce of this issue so it's unclear to me how this can be fixed, or if the issue is even with `redux-undo`

**Comment by beornborn** [comment]
@davidroeca just regular  `react-native init AwesomeProject`, `yarn add redux-undo@beta` and add import into index.android.js

https://github.com/beornborn/redux-undo-babel-bug-example

**Comment by davidroeca** [comment]
@beornborn I cloned the repo and was able to appropriately load the page on my machine. Didn't raise any build errors for me. 

```bash
$ yarn --version
1.1.0
$ node --version
v8.6.0
````

Try upgrading nodejs and yarn

**Comment by beornborn** [comment]
@davidroeca 

```
$ yarn --version
1.1.0
$ node --version
v8.6.0
```

http://prntscr.com/grt7qv

```
react-native init AwesomeProject
yarn add redux-undo@beta
```
add import into index.android.js

and run 
```
react-native run-android
```

if it helps we can arrange skype call with screen sharing: og.gorbunov

**Comment by davidroeca** [comment]
That was a bit of a trip downloading android studio and sdk, creating a fake project, downloading an android image, downloading a compatible jdk, and ensuring that ANDROID_HOME is set. Talk about a lot of moving pieces. Here's what I see:

```
yarn start v0.24.6
$ node node_modules/react-native/local-cli/cli.js start 
Scanning 577 folders for symlinks in /home/david/src/redux-undo-babel-bug-example/AwesomeProject/node_modules (4ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /home/david/src/redux-undo-babel-bug-example/AwesomeProject

React packager ready.

Loading dependency graph, done.
Bundling `index.android.js`  [development, non-minified, hmr disabled]  100.0% (302/302), done.
```

https://prnt.sc/grtoq2

Which of those things is raising the error on your system? The packager (`yarn start`) after the run-android command?

**Comment by beornborn** [comment]
@davidroeca yes, the packager while "Bundling `index.android.js`"

**Comment by davidroeca** [comment]
@beornborn just reproduced it, realized you were referring to the generated code

**Comment by davidroeca** [comment]
So I fixed this by manually removing the node_modules/redux-undo/.babelrc file. When `redux-undo` gets distributed, it is already transformed so you don't need the `.babelrc`. This is indeed an issue with the library.

I also got this to work by modifying the `.babelrc` and adding the following field: `"ignore": ["lib/"]` since `lib/` is already transformed. I'll create a PR for @omnidan to review--not sure if this or `npmignore`-ing `.babelrc` is the preferred approach

**Comment by omnidan** [comment]
released `beta9-9-7` with a fix for this

**Comment by benedyktdryl** [comment]
I have such version in package.json:

`"redux-undo": "1.0.0-beta9-9-7"`

And it's giving me same error:

```
ERROR in ./node_modules/redux-undo/lib/index.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "(...)node_modules/redux-undo/package.json" at 0, attempted to resolve relative to "(...)/node_modules/redux-undo"
```

Am I missed something?

**Comment by bdryl-softserve** [comment]
Actually, it's happening only when this dependency is not dev- dependency...

**Comment by davidroeca** [comment]
I think my PR didn’t fix it in that case. Babel shouldn’t care about this
because lib/ isn’t specified in “only”, but I guess we have to deal with
this behavior.

I think it’s a Babel version issue, but if it doesn’t work then we should
just migrate the config back out to babelrc and npmignore it. If we update
to Babel 7 that might also help.

See https://github.com/babel/babel/issues/4558

**Comment by davidroeca** [comment]
updating https://github.com/facebook/react-native/releases/tag/v0.50.0 should solve this issue as well

**Comment by ccoeder** [comment]
any improvements on this?

**Comment by omnidan** [comment]
@ccoeder is it still not working for you with the latest react-native and redux-undo release?

**Comment by iamhitarth** [comment]
@omnidan @davidroeca this issue is blocking us from working on our React Native app running on Expo SDK 29.0.0 (which uses React Native 0.55.4) with redux-undo 1.0.0-beta9-9-7.

Can you please check out the PR I've created to fix this by creating a .babelrc and adding to .npmignore? 

https://github.com/omnidan/redux-undo/pull/218
