### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by edo1493** [omnidan/redux-undo#183]
Hello, 

first of all, thanks for the great work! I have tried to make undoable one of my reducers in the following way: 

`const undoableFeed = undoable(feed, {
  filter: distinctState(),
  limit:1
})
`

I really need this functionality, but the result was the app slowed down really badly and the performance on other reducers dropped. I am currently using this on React Native and I got to the point where one of my components, an horizontal list was missing onclick events and lagging. 

After removing undo, everything went back to normal. I was wondering if you had seen something like this before and if there were any reasons why this should happen. Maybe I haven't configured it in the right way?

In a later stage, I have added the config object, at first, without it, the app was unusable.

**Comment by edo1493** [comment]
including single actions, removes every trouble. apologies.

**Comment by davidroeca** [comment]
Hi @edo1493,

Try installing the latest beta `redux-undo@1.0.0-beta9-9-6` and see what happens. In that version, distinctState is implicitly implemented--I'd recommend taking a quick look at the readme in this repo (as compared to npm)

https://github.com/omnidan/redux-undo/blob/master/package.json#L3

**Comment by edo1493** [comment]
Okay, I have removed distinctState and used includeAction. I see a slight improvement, but I can still notice the app is faster without redux-undo. I am about to try the beta.

**Comment by edo1493** [comment]
With the beta, I am getting: 
`"TransformError:node_modules/redux-undo/lib/index.js: Unknown plugin \"add-module-exports\" specified in \"emma/node_modules/redux-undo/.babelrc\" at 0, attempted to resolve relative to \"emma/node_modules/redux-undo\""`

**Comment by davidroeca** [comment]
Hm that sounds like https://github.com/omnidan/redux-undo/issues/182

**Comment by JannicBeck** [comment]
@edo1493 I experienced the same issues in my app with big state objects.

This is why I wrote these packages: [ngrx-undoable](https://github.com/JannicBeck/ngrx-undoable) and [undox](https://github.com/JannicBeck/undox).

**Comment by ccoeder** [comment]
I have the same error.

**Comment by RichardLindhout** [comment]
I noticed it when I debug my redux state. Have you tried it without?

**Comment by nmay231** [comment]
Yes, please try out @RichardLindhout 's suggestion. Otherwise, update to the *new* latest version (now `1.0.1`!) and see if that helps.

This looks like a stale issue so I'm going to close it for now. If there are still problems (or new ones), open a new one please. Cheers :+1:
