### ISSUE TITLE
How to include action A,  but exclude it when it is in a group with action B 

### ISSUE THREAD

**Issue by woodccc** [omnidan/redux-undo#185]
Thanks for the awesome library, appreciate for it ！

Now, I have a problem with it. At first ,thanks for every reply！

I have to include action A,and it works well.But need't include it when it is appear with action B.How could I do for this case?Any clue?

**Comment by davidroeca** [comment]
Hi @woodccc,

First check out #181 and let me know whether or not that helps--this may be a similar issue

**Comment by woodccc** [comment]
Hi @davidroeca ,
I already used groupBy,and it's very nice.And I scan #181 carfully,but my problem is still there.Let me show it in more detail.

First ,i need ACTION_A undoable.So need use includeAction.
```javascript
import { createAction } from 'redux-actions'

const undoableConfig = { 
    filter: includeAction([ACTION_A]) 
}

const func1 = () => {
    return dispatch => dispatch(createAction(ACTION_A)())
}
```

The rootReducer go on record when use func1.Then ,I want it not recorded when use func2.
```javascript
const undoableConfig = { 
    filter: includeAction([ACTION_A]) 
}

const func2 = () => {
    return dispatch => {
        dispatch(createAction(ACTION_A)())
        dispatch(createAction(ACTION_B)())
    }
}
```

Because use includeAction for filter ,the rootReducer is still go on record when use func2 . How to not recored when use func2?

And I try this , it still go on record when use func3.What I did wrong?
```javascript
import { get } from 'lodash'

const undoableConfig = { 
    filter: includeAction([ACTION_A]),
    groupBy: (action) => get(action, 'payload.undoableGroupName', null),
}

const func3 = () => {
    return dispatch => {
        const undoableGroupName = null
        dispatch(createAction(ACTION_A)({ undoableGroupName }))
        dispatch(createAction(ACTION_B)({ undoableGroupName }))
    }
}
```

Thanks anyway!

**Comment by davidroeca** [comment]
Okay with these examples, groups are probably not what you're after. Maybe add an `undoableFiltered` property to each payload. And add an additional filter function:

```js
const customFilter = (action) => get(action, 'payload.undoableFiltered', true)
const undoableConfig = {
  filter: combineFilters(includeAction([ACTION_A]), customFilter)
}

const func3 = () => {
  return dispatch => {
    dispatch(createAction(ACTION_A)({ undoableFiltered: true }))
    dispatch(createAction(ACTION_B)({ undoableFiltered: true }))
  }
}
```

**Comment by woodccc** [comment]
That's awesome! Be grateful for your patient responses！
