### ISSUE TITLE
Cannot rehydrate redux store using redux-offline

### ISSUE THREAD

**Issue by raynor85** [omnidan/redux-undo#187]
redux-offline allows rehydration of the redux store each time I relaunch the app (at the very basic). After enhancing an existing reducer with undoable, I noticed that the action 'persist/REHYDRATE' dispatched from redux-offline doesn't restore the changes for the enhanced undoable reducer, even if I manually dispatch the action any time during the app execution.
I have tried with the option ignoreInitialState: true, but still no luck.

**Comment by davidroeca** [comment]
@raynor85 redux-undo restructures your state tree from
```js
{ stateTowrap: data }
```
to
```js
{ stateToWrap: {
  past: [],
  present: data,
  future: [],
  // ... plus a few more attributes
}}
```

This is likely part of the problem. If you rehydrate an old state that doesn't have this strucutre, redux-undo will be pointing to the old state structure and won't know what to do with it. If there's a way to use the function i've exported in https://github.com/omnidan/redux-undo/pull/184 when rehydrating a state that has the old structure, then that may resolve the issue.

**Comment by raynor85** [comment]
The 'persist/REHYDRATE' action payload dispatched by redux-offline has already the new state (past, present, future), so I suppose it should already work out of the box.

**Comment by raynor85** [comment]
Ok I think I managed somehow. The point is that I totally forgot the shape of the state when the action reaches the enhanced reducer, which is the normal shape without past, present future. The 'persist/REHYDRATE' action payload contain everything, so I just needed to add in my reducer the following:

`case 'persist/REHYDRATE':
    return { ...action.payload.[undoableReducerName].present }`
