### ISSUE TITLE
Question: what's going on with clearHistory?

### ISSUE THREAD

**Issue by brmscheiner** [omnidan/redux-undo#188]
I would like to use clearHistory for my project and it's not working as expected. I see this is a beta feature, so I definitely shouldn't have expected anything =). I just wonder if clearHistory works under any conditions, and whether I can create those conditions in my project. Alternatively, if this is a quick fix I would be down to contribute.

**Comment by atgillette** [comment]
Looks like version ^1.0.0-beta2 is working.  But not ^0.6.1.

**Comment by omnidan** [comment]
@brmscheiner you need to use the beta version by installing `redux-undo@beta`, then it should work.

**Comment by brmscheiner** [comment]
@omnidan sounds good
