### ISSUE TITLE
compatible with redux-immutablejs

### ISSUE THREAD

**Issue by elaijuh** [omnidan/redux-undo#19]
Since the plugin will mutate store tree to add post, future, present properties, it's not compatible with redux-immutablejs. Is it possible to check the store type, if immutable then deal with immutable apis?

**Comment by omnidan** [comment]
@elaijuh redux-undo does *not* mutate the state! It only wraps the existing state with the history. This is called a [higher-order reducer](http://rackt.org/redux/docs/recipes/ImplementingUndoHistory.html). It should work fine with Immutable.JS, feel free to try it out :smile:

If you're running into any issues please reopen and post a gist with the not working code :wink:
