### ISSUE TITLE
Is there a way to pass initial history for a specific reducer?

### ISSUE THREAD

**Issue by amartacus** [omnidan/redux-undo#192]
I created an initialState object which contains the history for the todos reducer and I'm passing it to `createStore` along with the root reducer.  When my page renders I am able to access the todos.present but my todos.past is an empty array, is there a specific reason for this? I saw [this section](https://github.com/omnidan/redux-undo#initial-state-and-history)  on the docs where initial state can be added but it doesn't seem to work when creating the store from a rootReducer via `combineReducer`.

Here is my code snippet:
```
const initialState = {
  todos: {
    past: [[
      {
        id: '5c62c2ba-5',
        text: 'Take a Nap',
        completed: false
      }
    ]],
    present: [
      {
        id: '5c62c2ba-5',
        text: 'Take a Nap',
        completed: false
      },
      {
        id: '6c62c2ba-6',
        text: 'Put clothes in the dryer',
        completed: true
      }],
    future: []
  }
};

const todoApp = combineReducers({
  todos: undoable(todos),
  visibilityFilter
});

const store = createStore(todoApp, initialState);
```

Thanks in advance,

**Comment by omnidan** [comment]
@amartacus can you please provide a small repo/snippet that reproduces this issue? I copied the code you posted over to my redux-undo-boilerplate (and changed `counter` to `todos`), it seems to work fine there. Both `past` and `present` contain the proper items after store initialization.

**Comment by nmay231** [comment]
Was able to reproduce the issue with `redux-undo@0.6.1` but works fine in `redux-undo@beta-9-9-7`.

Will close with first stable release 1.0

**Comment by nmay231** [comment]
1.0 is released :+1:
