### ISSUE TITLE
[question] Present is never changed on UNDO/REDO, what am I not understanding?

### ISSUE THREAD

**Issue by chrillewoodz** [omnidan/redux-undo#194]
Like the title says, what am I missing here? If I click on an undo button, the past is changed like expected. But the `present` state remains the same, is this intended behaviour? 

If I have a subscription like:

```
    this.pagesSubscription = this.store.select('pages')
      .map((state) => state.present)
      .subscribe((state) => {
        console.log(state);
        this.pages = state;
      }
    );
```

I expected `this.pages` to change since I've pressed undo.

**Comment by omnidan** [comment]
@chrillewoodz the `present` state should change accordingly. which version are you using? how are you using `undoable`? can you provide a small repo/snippet to reproduce this issue?

**Comment by chrillewoodz** [comment]
@omnidan Sadly the project I was working on has been abandoned so I can't give you a reproduction case, therefore I'll close this issue.
