### ISSUE TITLE
Rather than store enhancer, this should be higher order reducer

### ISSUE THREAD

**Issue by gaearon** [omnidan/redux-undo#2]
I don't think `undo` should be a store enhancer. It should be a higher order reducer: `(reducer, options) => enhancedReducer`.

This would allow you to implement Undo/Redo for different parts of the tree in response to different actions, e.g.

```js
let rootReducer = combineReducers({
  todos: undoable(todos, { undoActionType: 'UNDO_TODOS', historyLength: 5 }),
  counter: undoable(counter, { undoActionType: 'UNDO_COUNTER', historyLength: 10 }),
  somethingElse // no undos here
})
```
The app would then be able to read `state.todos.currentState`, `state.counter.currentState`, or even `state.todos.history` to display the list of undoable actions (a la Photoshop).

This would also fix #1.

**Comment by gaearon** [comment]
Please also see http://package.elm-lang.org/packages/TheSeamau5/elm-undo-redo/2.0.0 for inspiration because it's essentially the same thing.

**Comment by omnidan** [comment]
Thank you so much for the suggestion - this has made everything so much cleaner :grin:

I also updated the README.md and the `redux-undo-boilerplate`, devtools work fine too now :ok_hand:

@gaearon please let me know if you still have any concerns or if it looks okay now
