### ISSUE TITLE
how can i redo or undo a async action 

### ISSUE THREAD

**Issue by gwl002** [omnidan/redux-undo#203]

**Comment by bbbbx** [comment]
Maybe [redux-thunk](https://github.com/gaearon/redux-thunk) middleware can resolve your problem :)

**Comment by omnidan** [comment]
currently the only way to do this is to dispatch a request when an undo/redo action happens, e.g. via subscription.

you might want to look into https://github.com/powtoon/redux-undo-redo, which takes a different approach than this library - where you define a reverting action for each action.
