### ISSUE TITLE
Unexpected key 'history' found in store

### ISSUE THREAD

**Issue by amtsh** [omnidan/redux-undo#207]
The redux store contains 'history' key as follows.

**Actual**

`past:[]
present:{}
future:[]
history:{past:[],present:{},future:[]}
`

**Expected**
`past:[]
present:{}
future:[]
`

This is creating unwanted duplication.

Can be reproduced here: https://snack.expo.io/rypiw7Ogm

**Comment by jackmac92** [comment]
@amtsh you are using redux-undo v0.6.1 when master README refers to v1. Use 
````
yarn add redux-undo@next
````
to get the latest
