### ISSUE TITLE
New filter API?

### ISSUE THREAD

**Issue by fforw** [omnidan/redux-undo#208]
Hi.. when looking through the changes for the 1.0.0-beta branch I notice fundamental changes to the context of filter functions and I wonder if I misunderstand them or if they are going into the wrong direction.

Is it possible to filter actions based on the next state, the state after applying the action? Because that seems to me the single best way to define undo filters.
I sort my redux state tree so that all undoable data is in a limited number of slices. If an action changes any of those slices as determined by instance equality, the action is considered undoable.

This way I don't need to classify my actions at all, but instead they get sorted by the effects they cause.

Would be a shame to lose that ability.

**Comment by nmay231** [comment]
Looking through the branch history, I do not notice any differences in API. The main change I notice is that the original `distinctState()` filter is now automatically applied (and is now deprecated).

You can still pass a custom filter function
```js
filter: function(action, newState, history) {
    let {past, present, future} = history // Access the current history
    newState // Or the state after the action's effect

    // Only add to history if different state (This filter is now automatically applied)
    return newState !== history.present
}
```

Let me know if you still have questions :+1:
