### ISSUE TITLE
Not able to import redux-undo

### ISSUE THREAD

**Issue by yume117** [omnidan/redux-undo#210]
I'm trying to use redux-undo in my angular 6 / typescript project with `ngrx`

I added it with `npm install --save redux-undo` with no problem, but when I'm trying to import it in any class with : 

`import undoable from 'redux-undo';`

Angular tell me that he `cannot resolve definitions for module 'redux-undo'`

Any idea what I could be doing wrong ?

**Comment by omnidan** [comment]
@yume117 the `0.x` version of redux-undo does not support ES6 imports. Use the `@beta` version.

**Comment by yume117** [comment]
Ok that correct my issue thank you for the quick answer

**Comment by lidaof** [comment]
I am having this issue for the beta version too..
but it only happens when I modify a file and webpack reloads...

Cannot find module 'redux-undo'.

**Comment by omnidan** [comment]
@lidaof see https://github.com/omnidan/redux-undo/issues/212#issuecomment-430604773
