### ISSUE TITLE
Cache is not reset after creating a new store

### ISSUE THREAD

**Issue by skamril** [omnidan/redux-undo#214]
```javascript
const reducer = undoable(
  combineReducers({
    foo: (state = {}, action) => state
  })
);

const preloadedState = { foo: { bar: 1 } };

let store = createStore(reducer, preloadedState);
console.log(store.getState().present.foo); // { bar: 1 }

// Then with undefined `preloadedState`
store = createStore(reducer);
console.log(store.getState().present.foo); // { bar: 1 }
// The cache is not reset, expected value is {}
```
[![Edit k9rv5515n5](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k9rv5515n5)

The issue can be fixed with a condition, but I don't know if it's the good way:
```javascript
// src/reducer.js
// ...
export default function undoable(reducer, rawConfig = {}) {
  // ...
  let initialState = config.history
  return (state = initialState, action = {}, ...slices) => {
    if (action.type === "@@INIT") {
      initialState = config.history
    }
    // ...
  }
}
```

**Comment by nmay231** [comment]
@skamril, that change to the code would definitely "fix" the problem, but that is the intended behavior as it stands. One ability of redux-undo is to reset the whole state/history back to when it was initialized. This is done when `@@INIT` or another action type in `initTypes` ([config](https://github.com/omnidan/redux-undo#configuration)) is dispatched.

Besides, Redux discourages [using more than one store](https://redux.js.org/faq/store-setup#can-or-should-i-create-multiple-stores-can-i-import-my-store-directly-and-use-it-in-components-myself) making this an unreachable condition in normal circumstances.

> As with several other questions, it is *possible* to create multiple distinct Redux stores in a page, but the intended pattern is to have only a single store. [emphasis is theirs]

When there is a legitimate reason for multiple stores, like maybe in your case, it would be best to rewrap your reducer with `undoable` each time.

```js
let store = createStore(
  combineReducers({
    ...otherReducers,
    foo: undoable(fooReducer)
  }),
  { foo: { bar: 1 } } // initialState
);

let store2 = createStore(
  combineReducers({
    ...otherReducers,
    foo: undoable(fooReducer)
  })
  // Here, initialState is set to undefined
);
```

A similar issue has come up in #213 as well, so maybe this needs to be more thoroughly documented.

I will leave this issue open as a reminder to add it to the docs. Mention me if you have additional questions/concerns :+1:

**Comment by skamril** [comment]
Thanks for the answer. I fixed my issue since by never give an undefined `preloadedState`, but it's good to know for the next time.
