### ISSUE TITLE
Actioncreators.undo mutates the state in array of objects

### ISSUE THREAD

**Issue by hshyk** [omnidan/redux-undo#219]
I have an array of objects within the Redux store. When I update a property that is inside one of the objects, and run the undo, it works fine.  When I rearrange the objects inside the array, and run the undo action, it doesnt undo and mutates the past and present to the current state.  If I just make changes to the state (with no undo), then it does keep the store history correctly (checked via Redux dev tools).

**Comment by TigranWeb** [comment]
You are need create new array and pass it to store after filtering, in array you are filtering links to objects not objects himself.
one possible way is 
`
const newArray = JSON.parse(JSON.stringify(oldArray));
`

**Comment by hshyk** [comment]
That worked! Thank you!
