### ISSUE TITLE
Inconsistency between source code and npm published package

### ISSUE THREAD

**Issue by ZuchaoWang** [omnidan/redux-undo#221]
I see the following source code in src/reducer.js (line 185-186):

`case actionTypeAmongClearHistoryType(action.type, config.clearHistoryType):
        res = createHistory(history.present, config.ignoreInitialState)`

But in the npm published package (v1.0.0-beta9-9-7), in lib/reducer.js, the corresponding code misses `config.ignoreInitialState`, which becomes:

`case actionTypeAmongClearHistoryType(action.type, config.clearHistoryType):
        res = createHistory(history.present);`

I want the source code version with `config.ignoreInitialState`, but I can only install the npm package version without that. Is this a bug?

**Comment by nmay231** [comment]
Sorry for the delayed response.

No, this is not a bug. We are just now working on pushing ver 1.0. If you need to install the latest version from Github, add this to your `package.json`

```js
"redux-undo": "omnidan/redux-undo#master"
```
