### ISSUE TITLE
Typescript: clearHistoryType should be typed as a string[]

### ISSUE THREAD

**Issue by nicosantangelo** [omnidan/redux-undo#222]
`clearHistoryType` supports both [a string and an array of strings](https://github.com/omnidan/redux-undo/blob/8845c52b6aadbe5cc738131028198072c2ff56bd/src/reducer.js#L94) (beta only) but the type on [typings.d.ts](https://github.com/omnidan/redux-undo/blob/master/typings.d.ts#L60) says `string?`

Shouldn't it be `clearHistoryType?: string || string[];` ?

**Comment by nmay231** [comment]
Resolved in #248 :+1:
