### ISSUE TITLE
Typescript bug: AnyAction type

### ISSUE THREAD

**Issue by troygibb** [omnidan/redux-undo#229]
Hello, was just getting started with your library when I came across a typescript issue: 

```typescript
const rootReducer = combineReducers({
  userInput: undoable(userInputReducer)
})
```
Which produces the following typescript error:

```
...
Type 'AnyAction' is not assignable to type 'IUserInputActionTypes'.
...
```

Since `undoable` is not parameter-ized to accept action types as an type def argument, I have no way around this issue without sacrificing typesafety--unless I'm missing something? Any help appreciated!

**Comment by Asatelit** [comment]
@omnidan, please take a look at my [PR ](https://github.com/omnidan/redux-undo/pull/232) that will add the ability to use type checking reducers, eg:
`const application = combineReducers({
  model: undoable<ModelState, ModelActionTypes>(modelReducer),
  editor: editorReducer,
});`

**Comment by nmay231** [comment]
Apologies for the delay. #232 reviewed and merged :+1:
