### ISSUE TITLE
GroubBy is not working

### ISSUE THREAD

**Issue by jithinkradhakrishnan** [omnidan/redux-undo#231]
Hi Can I Give multiple action in 

undoable(reducer, { groupBy: groupByActionTypes([SOME_ACTION1,SOME_ACTION2,SOME_ACTION3]) })

**Comment by pgonzalez-santiago** [comment]
Same here.

What I did was exclude one of the actions

`filter: excludeAction(SOME_ACTION)`

**Comment by nmay231** [comment]
Yes, it is certainly possible to pass multiple action types to the `groupByActionTypes()` helper function. Would you clarify how `groupBy` is not working for you?

`groupByActionTypes` will group consecutive actions *of the same type* into one undo/redo. For example with the actions A, B, C, they will be grouped like this
`[A A A] [B B] [C] [A A] [B B]`
