### ISSUE TITLE
Dispatch an action to change undo limit?

### ISSUE THREAD

**Issue by joshwcomeau** [omnidan/redux-undo#235]
Hi there,

Thanks for the terrific library; it saved me _a ton_ of trouble. My project is a week ahead because of redux-undo :D

This is a feature request (or possibly not, if it already exists). I'd like to be able to dynamically change the size of the history stack.

Right now it's set with a static `limit` option:

```
undoable(reducer, { limit: 100 });
```

I'd like to have a setting in my app where users can change the size of the undo stack, so that folks with tons of spare memory can increase it beyond the default. 

I took a peek at the source and this seems like something that could be implemented with a new action that the higher-order reducer listens for, like `updateLimit`. It could have a default type but allow users to override it, similar to `jumpToPastType` and friends.

I'd be happy to take a shot at implementing this, if this sounds like a worthwhile addition? No worries if you'd rather not increase the size of the API, I can always work on my own fork.

**Comment by nmay231** [comment]
This is an interesting idea to bring to the table!

However, I don't know if this is useful for the majority of users, and implementing this would add more runtime overhead and complicate the API.

What you can do to make this work (if you haven't solved this problem already) is have a hard max limit that users can not go past and then write a custom Higher-Order reducer that crops the `past` to stay within your scalable limit.

```js
const limitWrapper = (undoableReducer) => (state, action) => {
    const newState = undoableReducer(state, action)
    const limit = getScalableLimit()
    return {
        ...newState,
        past: newState.past.length > limit
            ? newState.past.slice(1)
            : newState.past
    }
}

export default limitWrapper(undoable(myReducer,
    {
        limit: 1000 // Some value greater than or equal to the max scalable limit
    },
))
```

In the future, there might be a more customizable interface for adding little "helpers" like this one without overloading the API for everyone, and this would work perfectly as one of them.
