### ISSUE TITLE
Explicitly know it's an "undo / redo" action?

### ISSUE THREAD

**Issue by xxlee0927** [omnidan/redux-undo#236]
Similar issue to #162.

Consider the situation that setting limit to 10 and current index is 9 (i.e. the 10th step).
``` js
{
  index: 9,
  limit: 10
}
```
then perform undo
``` js
{
  index: 8,
  limit: 10,
}
```
then 
1. redo it
``` js
{
  index: 9,
  limit: 10,
}
```
2. do a new operation
``` js
{
  index: 9,
  limit: 10,
}
```
Both has same result.
How do I explicitly detect the last redo action with only `index` and `limit`?

**Comment by nmay231** [comment]
Hmm. I see what you mean. I don't think there is a way to do this directly still. Maybe this calls for a feature request...

On the other hand, why you would need to distinguish between an undo and a redo that restores to the exact same state? That is, if a user undoes then redoes an action, what is the difference between that and manually doing the same action? I don't see why you would want to treat them differently.

If you *do* need to distinguish them, you can filter certain actions like [the original comment](https://github.com/omnidan/redux-undo/issues/162#issuecomment-301554356) says to.

Alternatively, you can pass `neverSkipReducer: true` as an option and then handle the differences manually:
```js
case REDUX_REDO:
    if (/* need to change state manually */) {
        // Do it
    }
case NORMAL_ACTION:
     // Otherwise handle it normally
```
Let me know if that helps. :+1:

**Comment by xxlee0927** [comment]
My project is performing annotation on canvas. (like sketching on canvas)
When undo or redo, I need to run some init function **in component** to change some component state.
The init function only need to be run when undo or redo due to I don't know how user get to that state, with what operation.

**Comment by nmay231** [comment]
Checking for an undo is easy. Just see if `state.future.length > 0` in `componentDidUpdate` or with a `useEffect` hook and call the `init` function. To catch redos, you will need to save the length in a piece of state like `numberOfUndos`.

Now you have two cases: either the user redoes the action or the user runs the action manually. If they run it manually, set `numberOfUndos` to zero *while handling their action* and proceed normally. If it is a redo, `numberOfUndos` will still be one (or more than one) but `state.future.length` will be zero. Check if they are different and then run the init function to set everything up.

Does that work for you?

**Comment by xxlee0927** [comment]
Is there some example code of this? I'm not sure I understand your thought properly. But if the key is checking `state.future.length`, I think this issue would not be handled. In component I detect `index` in `useEffect` then perform another condition check to check whether it's an undo/redo or not.
Using the situation above:
```
{
  index: 8,
  limit: 10,
  future.length: 1
}
```
No matter I redo or do a new operation, these three attribute will have same result.

I think if there is a new attribute like
```
changedByType: 'undo' | 'redo' | 'manually'
```
and set this attribute according `undoType` and `redoType`, this issue can be handled gracefully. I only have to check `index` change and `changedByType`, other things are handled by this higher order reducer.

**Comment by nmay231** [comment]
Here is some example code.

```jsx
const [previousFutureLength, setPreviousFutureLength] = useState(0)

const handleManualAction = () => {
    // Set to zero on manual action
    setPreviousFutureLength(0)
    dispatch(MY_ACTION)
}

useEffect(() => {
    if (state.future.length > previousFutureLength) {
        // An undo must have been called. Handle it and update previousFutureLength
        setPreviousFutureLength(state.future.length)

    } else if (state.future.length < previousFutureLength) {
        // This *must* be a redo because if MY_ACTION was dispatched then
        // previousFutureLength would be reset to zero which equals `future.length`
        setPreviousFutureLength(0)
    } else {
        // No need to do anything here. Component state in sync with redux
    }
}, [state.future.length])

return (
    <>
        <button onClick={handleManualAction}>Manual action</button>

        {/* Notice previousFutureLength is unchanged in these actions */}
        <button onClick={() => dispatch(UNDO)}>undo</button>
        <button onClick={() => dispatch(REDO)}>redo</button>
    </>
)
```

At the moment, it would be best to keep the size of the API low until we implement a more general, extendable method of adding fields to the state. Unless it's clear more users need this by default, this feature implementation will probably wait until then.

Thanks for your patience.
