### ISSUE TITLE
Debounce/delay storage of state in history

### ISSUE THREAD

**Issue by subblue** [omnidan/redux-undo#24]
I'm interested to use redux-undo to replace an ad-hoc undo implementation I currently have in my app. One thing I'm wondering about is being able to delay/debounce the storage of the app state for situations where a text input or slider might be changing and there will be a stream of rapid state changes.

I currently use a simple clearTimeout & setTimeout of 1000ms after which the state is stored in the history object. Then each undo action gives a sensible undo change (rather than having to step back through tens of tiny changes of a slider value or every character of a word typed into an input box).

I'm wondering how a similar thing could be achieved using redux-undo?

Thanks!

**Comment by omnidan** [comment]
Yes, that's totally possible with an [action filter](https://github.com/omnidan/redux-undo#filtering-actions). You can keep using your current system, too (I haven't tried the code, though):

```js
let filter
undoable(reducer, function filterActions(action, currentState, previousState) {
  if (!filter) {
    filter = setTimeout(() => { filter = false }, 1000)
    return true
  }
  return false
})
```

I hope this helped you, if you have any further questions don't hesitate to ask :smile:

**Comment by subblue** [comment]
Thanks for your answer, but I don't think this is quite what I'm aiming for. 

Your action filter will prevent the state being added to the history for a period of time, but after the timeout there is nothing to trigger the history to be updated with the new state (unless there is something else happening behind the scenes?)

Imagine an input box that triggers a state change on every keypress. I don't want to store a new history entry for every individual key event, but only after there hasn't been a keypress for at least 1000 ms. Only then the present state should be saved in the history.

I suppose alternatively I could somehow update just the ```present``` attribute of the history object if the update occurs within a threshold time (rather than shifting it onto the past array), but that doesn't seem particularly tidy.

**Comment by omnidan** [comment]
@subblue Ah, I get you now. I think the better way to do this is doing it in the component. That way you can only send/dispatch the event if there hasn't been another keypress for at least X ms.

**Comment by omnidan** [comment]
@subblue Have you solved this issue yet? :smile:

**Comment by subblue** [comment]
In the end I rolled my own implementation which is a mix of this lib and the example given in the Redux docs as I needed a couple of other special bits.
My implementation keeps track of the last update time, and if there is another update within the time threshold it just replaces the last state rather than appending a new one. This stops the undo history growing for every little quick change.

**Comment by omnidan** [comment]
Sounds good, glad you figured it out :ok_hand: - would be a good case for a [higher-order reducer](https://github.com/rackt/redux/blob/master/docs/recipes/ImplementingUndoHistory.md#meet-reducer-enhancers) (if it isn't already one).

**Comment by lostfictions** [comment]
Hey @subblue, do you happen to have your custom implementation viewable anywhere? I'm facing this same problem. I was thinking I might be able to get what I need by duct-taping this, [redux-batched-subscribe](https://github.com/tappleby/redux-batched-subscribe), and lodash's debounce together somehow, but it's tricky enough that I'd rather not solve it from scratch if I don't need to.

**Comment by lostfictions** [comment]
(In particular, it's not totally clear to me from the redux-undo docs whether there's any way to cleanly update the `present` state without pushing anything new to the undo history. Without that, it seems like it'd be a lot more difficult to handle all sorts of little edge cases around debouncing...)

**Comment by omnidan** [comment]
@lostfictions if an action is filtered by a `filter` function, it still changes `present`, but doesn't update the history: https://github.com/omnidan/redux-undo/blob/master/src/index.js#L239 - hope I could help you a bit :)

**Comment by lostfictions** [comment]
Ah, thanks! I'll try and make this work then :)
