### ISSUE TITLE
undo don't work when using undoType and redoType 

### ISSUE THREAD

**Issue by arfanliaqat** [omnidan/redux-undo#241]
I've been unable to make redux-undo dispatch custom action types as described in docs.

Minimal reproduction:  https://codesandbox.io/s/eager-mcnulty-5gbzs?fontsize=14

// this causes error ( to be exact it doesn't update present state and doesn't state to future either hence redo is not available)
```
export default combineReducers({
  counter: undoable(counterReducer, {
    undoType: "CUSTOM_UNDO",
    redoType: "CUSTOM_REDO"
  })
});
```

// this works fine
```
export default combineReducers({
  counter: undoable(counterReducer)
});

```

**Comment by omnidan** [comment]
@arfanliaqat you need to use your custom actions instead of `ActionCreator.undo()` and `ActionCreator.redo()`. I have fixed your example: https://codesandbox.io/s/lucid-poitras-8fowp
