### ISSUE TITLE
Cannot undo when state is an array

### ISSUE THREAD

**Issue by PepperYan** [omnidan/redux-undo#25]
I saw redux-undo on redux doc. When I trying to use it in my demo project, I found it not work at all when the state is an array. Without undoable, everything is just fine. After I use undoable wrap my reducer, the state became an Object, but it should be an array.

**Comment by PepperYan** [comment]
Sorry,that is my fault. I didn't use it right

**Comment by omnidan** [comment]
@PepperYan yes, you have to access `.present` to get the state after wrapping your reducer with `undoable`. Glad you figured it out :smile:
