### ISSUE TITLE
Create example for converting regular reducer to an undoable one

### ISSUE THREAD

**Issue by nmay231** [omnidan/redux-undo#255]
Hello and welcome to Redux-undo! This issue is asking newcomers to open source for their help. If that's you then great!

We need good examples to show new users of the library how to, well... use the library!

The task is to create an example in `docs/main/examples/` showing how to convert an existing reducer to an undoable one. You should show how the state is changed from

```js
{
    state: {
        field1: 'data',
        // ...
    }
}
```

to the following form.

```js
{
    state: {
        past: [ ...previousStates ],
        present: { field1: 'data', /*...*/ },
        future: [ ...futureStates ],
        // ...other fields redux-undo needs
    }
}
```

**Note:** The wrapped reducer still deals with the same state, i.e. you don't need to change your reducer.

If you are feeling creative, you can make up the example state. As a suggestion, you can have the original state be the list of labels for GitHub ([see here](https://github.com/omnidan/redux-undo/labels))

```js
{
    labels: [
        {
            text: 'bug',
            color: '#ff0000', // hexadecimal color
            desc: 'Something in this project needs to be fixed',
        },
        // ... More labels
    ]
}
```

Again, you can choose whatever state you wish.

**If you are interested in doing this, reply to this issue. I'll get back to you to see if you have any questions and show you how to get started!**

Instructions:
- Reply to this issue. And while you are waiting, you can...
- Read the [contributing guide](https://github.com/omnidan/redux-undo/blob/master/CONTRIBUTING.md) if you have not already (don't worry about the instructions for contributing code, this is a doc contribution).
- Since this is a relatively simple doc change, you can just create a fork using the button in the top right and make the file in your fork.
- Create the doc `docs/main/examples/basic-example.md` and document what is listed above.
- Link to it from `docs/main/examples/readme.md` and also `docs/summary.md`. These updates will be reflected on the gitbook site after merging (https://redux-undo.js.org).
- And feel free to ask questions! If you are ever uncertain about something, ask me here in this issue and I can help.

**Comment by mohinderps** [comment]
I am up for this.

**Comment by nmay231** [comment]
@mohinderps Awesome! You can go ahead and get started.

And if you are ever uncertain about some of the nuances of redux-undo or have any other questions, just let me know :+1:

**Comment by mohinderps** [comment]
Thanks @nmay231.

**Comment by mohinderps** [comment]
Created PR #262

**Comment by nmay231** [comment]
#262 merged :wink:
