### ISSUE TITLE
Posible error in documentation

### ISSUE THREAD

**Issue by pichoneto** [omnidan/redux-undo#26]
Hello,

This may be a mistake on my side, but when trying to create a custom filter I wasn't able to make it work and when using the helpers you provide, it worked great. Later, I discovered that when using the helpers, the documentation says to use this line:
<code>undoable(reducer, { filter: includeAction(SOME_ACTION) })</code>
and when using a custom function, to use this:
<code>undoable(reducer, function filterState(action, currentState, previousState) {
  return currentState !== previousState; // only add to history if state changed
})</code>

As you can see, on the former undoable accepts filter as an object and on the latter as a function. I was only able to make my custom filter work when combining both:
<code>undoable(reducer, {filter: filterState(action, currentState, previousState) {
  return currentState !== previousState; // only add to history if state changed
}})</code>

Is this correct? Great work BTW
Greetings

**Comment by omnidan** [comment]
Good catch. This ~~is~~ was a mistake in the documentation. :sweat_smile: 

I have updated the examples to use the new `{ filter: function }` syntax: https://github.com/omnidan/redux-undo/commit/bf6f4eb3737c23faf2d5d2693a4bcdae8e460ca2

**Comment by pichoneto** [comment]
You're welcome!
