### ISSUE TITLE
History

### ISSUE THREAD

**Issue by YingshanDeng** [omnidan/redux-undo#28]
Hello! in the counter example, I found that the counter state not only has the `past`, `present`, `future`, but also has a property `history`, what's the role of `history`? How to remove it ? I think I only need `past`, `present`, `future`.  thank you!

![image](https://cloud.githubusercontent.com/assets/7246595/12444543/802cbe62-bf9a-11e5-9b1f-30f51de27226.png)

**Comment by YingshanDeng** [comment]
I found it！in the `wrapState` function, you wrap the history into state? why? Can I manually change it ?

From
``` JS
// wrapState: for backwards compatibility to 0.4
function wrapState (state) {
  return {
    ...state,
    history: state
  }
}
// /wrapState

// updateState
function updateState (state, history) {
  return wrapState({
    ...state,
    ...history
  })
}
// /updateState
```

To
``` JS
function wrapState (state) {
  return state;
}
```

**Comment by omnidan** [comment]
@YingshanDeng this is intentional to keep compatibility with 0.4 (where you could access the history with `state.history`). I might release 1.0 in a while and deprecate/remove this.

**Comment by YingshanDeng** [comment]
@omnidan  Thank you for your quickly reply! Come on : )

**Comment by omnidan** [comment]
@YingshanDeng would be great if you could contribute a PR that removes this, I'm kinda busy until February. :blush: If you don't have time either, don't worry, I'll do it (hopefully) soon :stuck_out_tongue:

**Comment by YingshanDeng** [comment]
@omnidan Ok, I will read the code again and have a try. Thank you for your work again!

**Comment by YingshanDeng** [comment]
@omnidan  Hi, I have remove the history property. And make a pr：）

**Comment by omnidan** [comment]
This is fixed with the merge of #29

**Comment by omnidan** [comment]
I have released a beta version of 1.0 with this change:

```
npm install --save redux-undo@beta
```

**Comment by YingshanDeng** [comment]
Great!👍👍

**Comment by kachkaev** [comment]
Thanks for posting this issue @YingshanDeng! I just installed redux-undo into a new project and noticed a recursive history tree, which did not show up in my previous app. Turned out I installed `redux-undo@beta` that time, but then forgot about about the caveat of the current `latest` :smile: Took a while to sort this out, but I finally did it, thanks to this thread.

@omnidan what are your plans on going forward with 1.0? This is an awesome library that does not appear to have any good competitors! Awesome stuff! :rocket:

**Comment by omnidan** [comment]
@kachkaev we still need some refactoring and better documentation for 1.0, everything else seems to be sorted out for now. Unfortunately I don't have too much time myself, so I would be very happy about contributions in any way (especially docs!)
