### ISSUE TITLE
Support ESM

### ISSUE THREAD

**Issue by HarelM** [omnidan/redux-undo#280]
#### I'm submitting a ...
  - [ ] Bug report
  - [x] Feature request
  - [ ] Docs update
  - [ ] Support request => Please do not submit support requests here, see note at the top of this template.

#### What is the current behavior/state of the project?
The project does not support esm build

#### What is the desired behavior?
Support esm module export

#### If this is a feature request, what is the use case for changing the behavior?
I'm using this code in an angular 10 application which now emit a compilation warning for modules that are not exported as ESM... :-(

#### Please tell us about your environment:
  
  - Library version: 1.0.1
  - Redux version: 4.0.5
  - Browser: all
  - Language: Angular 11 with typescript 4.0.5

#### Other information
See here:
https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by alexander-heimbuch** [comment]
This should be solved with 1.1.0
