### ISSUE TITLE
Why are Dependabot vulnerability fixes ignored?

### ISSUE THREAD

**Issue by dmathisen** [omnidan/redux-undo#307]
#### I'm submitting a ...
  - [x] Bug report
  - [ ] Feature request
  - [ ] Docs update
  - [ ] Support request => Please do not submit support requests here, see note at the top of this template.

#### What is the current behavior/state of the project?
Is there a reason none of the Dependabot security vulnerabilities have been merged? Is this repo being maintained?

![image](https://github.com/omnidan/redux-undo/assets/684701/f2e50c14-31ee-49b9-89e0-431db997f258)

**Comment by omnidan** [comment]
hi @dmathisen - unfortunately, I am not using the project myself right now and currently do not have time to maintain it. Like mentioned in the README, I am always looking for maintainers willing to take over the project ☺️  If you are interested, please let me know.

**Comment by dmathisen** [comment]
@omnidan Thanks for the update. Sorry I missed that in the README. Understood.
When I have time, I might try to dig in, update dependencies and fix my (and hopefully other) bugs. I'm glad to see that you're responsive (that's very reassuring), so I appreciate it. I hope to look into this a bit more next week and I'll be in touch. Thanks and talk soon.
