### ISSUE TITLE
Strange error on first use

### ISSUE THREAD

**Issue by iandanforth** [omnidan/redux-undo#37]
Trying out redux-undo and I get the following error (both at HEAD and beta). Not sure how to start debugging this. Any suggestions would be welcome!

```javascript
export const rootReducer = combineReducers({
    backLinkUrl: undoable(backLinkUrl),
});
```

```
Uncaught TypeError: (0 , _redux2.default) is not a function
```

**Comment by omnidan** [comment]
Can you try doing a clean install in a new project? Maybe clone and run [redux-undo-boilerplate](https://github.com/omnidan/redux-undo-boilerplate) to see if it's specific to your project configuration.

More information about your setup would be nice too - maybe a gist/github repo?

Thanks in advance. :smile:

**Comment by iandanforth** [comment]
Closing, this turned out to be related to another import made at the same time.

**Comment by omnidan** [comment]
@iandanforth maybe let us know what caused the issue in case someone stumbles upon the same problem later? :grin:

**Comment by RowiDont** [comment]
In case anyone runs into this. Make sure you're importing the function correctly:

- Yes: `import { combineReducers } from 'redux';`
- No: `import combineReducers from 'redux';`

I may or may not have been doing the latter :sob:

**Comment by omnidan** [comment]
Thanks for the comment @RowiDont :wink:
