### ISSUE TITLE
Clear stack?

### ISSUE THREAD

**Issue by iandanforth** [omnidan/redux-undo#38]
In an editor I'm building I'd like my 'save' and 'exit' methods to do the following:

save - Remove all past and future history
exit - Move to the the earliest history.

These don't appear to be built in (unless I'm missing something obvious). 

Any suggestions on accomplishing the above?

**Comment by omnidan** [comment]
You're right, this isn't implemented right now.

You can use `jumpToPast` to move to an earlier point in history, though.

**Comment by pl12133** [comment]
I gave this a shot in pl12133@cb20e3d (Ignore pl12133@20395b8, my fork was stale).

Is this the "remove all past and future history" behavior that you would be going for?

**Comment by omnidan** [comment]
@pl12133 looks really good! :grin: can you open a PR, please? :wink:

**Comment by omnidan** [comment]
Reopening because there is not a release including this yet.

**Comment by omnidan** [comment]
@iandanforth this is included in `beta4`, please let me know if it works fine for you :wink:

**Comment by iandanforth** [comment]
It does thanks! I've still got the "reset to oldest" action as well but
that should be a separate ticket.

**Comment by omnidan** [comment]
Cool - thanks for testing! Feel free to open another issue for that :wink:
