### ISSUE TITLE
Initial history does not work

### ISSUE THREAD

**Issue by neojski** [omnidan/redux-undo#43]
I tried these:

```js
  let reducerA = (state = "none", action) => {
    return state;
  };
  let reducerB = Redux.combineReducers({
    reducerA,
  }); 
  let store = Redux.createStore(undoable(reducerB, {
    initialState: {
      reducerA: "some"
    },  
    initialHistory: {
      past: [{reducerA: "past"}],
      present: {reducerA: "some (from history)"},
      future: [{reducerA: "future"}]
    }   
  }));
  debugger;


  let store2 = Redux.createStore(undoable(reducerA, {
    initialState: "some",
    initialHistory: {
      past: ["past"],
      present: "some (from history)",
      future: ["future"]
    }   
  }));
  debugger;
```

But the current state is `"none"` in both cases and the history is empty. In the second case if I don't set `state = "none"` initially the current state becomes `undefined`.

**Comment by pl12133** [comment]
Reproduced in pl12133@0aa8637.

Output with bug:
```
Store 1:  { past: [], present: { reducerA: 'none' }, future: [] }
Store 2:  { past: [], present: { reducerA: 'none' }, future: [] }
```

Attempt to fix: https://github.com/pl12133/redux-undo/commit/2311b24177f1e2af598ac3b4db69f2ec7f25f1f6

Output with fix:
```
Store 1:  { past: [ { reducerA: 'past' } ],
  present: { reducerA: 'some (from history)' },
  future: [ { reducerA: 'future' } ] }
Store 2:  { past: [ { reducerA: 'past' } ],
  present: { reducerA: 'some (from history)' },
  future: [ { reducerA: 'future' } ] }
```

This gives the side effect of `init` actions resetting to the `initialHistory`, is this the desired behavior? I believe this to be proper, if this fix provides the correct behavior then I can open up a PR.

**Comment by omnidan** [comment]
@pl12133 couldn't you just `return config.history || createHistory(res)`, which would still use the initialState defined by the reducer default value?

**Comment by pl12133** [comment]
@omnidan I think I see what you mean, in the case where there is no provided `initialHistory` or `initialState`, we should fall back to the `initialState` of the reducer. Perhaps it would be better to change the `config.history` property to:

```js
config.history = rawConfig.initialHistory || createHistory(config.initialState || reducer(undefined, {}))
```

This way returning `config.history` will always represent the first state put through the reducer.

**Comment by pl12133** [comment]
This issue made me realize weaknesses in the test coverage. I have revamped tests to run as a function of a configuration object, and added tests for `initialHistory` and `initialState`. These changes are up on [improve-tests branch](https://github.com/pl12133/redux-undo/blob/improve-tests/test/index.spec.js) and many of them are failing when run against master.

I continued work on #43 and fixed all the tests in pl12133@4029e1533f63bc51a79525f85fa2db4c1964e288 . I can merge the branches together if the changes in branch `issue-43-fix` seem acceptable.

I don't think the changes should break backward compatibility, they should just add the functionality that a reducer called with no arguments will always return its `initialState`, which I believe is standard behavior for a Redux reducer. Let me know what you think :+1:

**Comment by omnidan** [comment]
@pl12133 Sounds good. I really appreciate your work on redux-undo, you've been maintaining it really well while I've been busy :sweat_smile:

**Comment by pl12133** [comment]
@omnidan Thanks a lot for the add! I've learned a lot about testing by contributing so I am happy to do it.

I have a number of small changes on my fork, I will open them up as separate PR's so changes can be discussed separately.

**Comment by omnidan** [comment]
@pl12133 Cool - I made a [gitter chat](https://gitter.im/omnidan/redux-undo) to make it easier to talk about changes :)

**Comment by omnidan** [comment]
@neojski @pl12133 This should be fixed in the new `beta4` release - can you test it and let me know if this can be closed?

**Comment by neojski** [comment]
@omnidan, I gave [1.0.0-beta4] a try and it doesn't seem to work. It looks like the [change](https://github.com/pl12133/redux-undo/commit/4029e1533f63bc51a79525f85fa2db4c1964e288) is not included into that release.

**Comment by pl12133** [comment]
@neojski In `beta4`, `initialHistory` was removed in favor of using the second argument to `Redux` `createStore(reducer, initialState)`.

`initialHistory` might come back by the time `1.0.0` is released, for now we are trying with the `createStore` way to see how it works.

**Comment by neojski** [comment]
I'm looking at [the documentation](https://github.com/omnidan/redux-undo/tree/d6dca65ae033edfeab33ffc95f76db4d77ce2b7d#initial-state-and-history) and I can't tell the difference between first example and the second one. How do you distinguish between the second argument being `initialHistory` vs just `state`? Is it that you're magically checking if the second argument _looks_ like a history object?

**Comment by pl12133** [comment]
Thats correct, `undoable` will figure out if your `initialState` is a history and if it is not it will make it into a history for you.

**Comment by neojski** [comment]
This seems quite sketchy to me. I could imagine people being surprised why this behaves differently depending on whether their state object contains `present` property or not.

**Comment by tiemevanveen** [comment]
And contain `past` and `future` by coïncident? Maybe we should add some more documentation?

**Comment by neojski** [comment]
Some more documentation would be great. It's also not very clear what's gonna happen if you skip `future` because, say, you care only about `past` and `present`.

**Comment by tiemevanveen** [comment]
Fair point

**Comment by omnidan** [comment]
Closing this as it's been superseded by #88 - feel free to comment there, reopen or open a new issue if you feel it's necessary :wink:
