### ISSUE TITLE
[SEO] Add "higher order reducer" to documentation

### ISSUE THREAD

**Issue by pl12133** [omnidan/redux-undo#46]
Right now, when you google "higher order reducer" your other packages `redux-ignore` and `redux-recycle` both come up first but this one does not. Consider adding this phrase to the documentation if you wish to have all three show up on Google and Github search results.

**Comment by omnidan** [comment]
Thanks for the suggestion! I updated the description to be: *higher order reducer to add undo/redo functionality to redux state containers*

It now matches the other descriptions:

 * higher-order reducer to ignore redux actions
 * higher-order reducer to reset the redux state on certain actions

Do you have any other suggestions for SEO? :grin:
