### ISSUE TITLE
write unit tests

### ISSUE THREAD

**Issue by omnidan** [omnidan/redux-undo#5]

**Comment by omnidan** [comment]
I started writing unit tests with [speckjs](https://speckjs.github.io/), but it doesn't work for me (at least not how I want to use it :sweat_smile:): https://github.com/speckjs/speckjs/issues/150

**Comment by hex13** [comment]
I've debugged it. First it looks like you were passing wrong arguments to the `speck.build`. I rewrite this in this way:
https://gist.github.com/hex13/315abfbd3e9e2f37e626
But there other issues (ES6 related) and I wrote about thes on speckjs's issue you created. https://github.com/speckjs/speckjs/issues/150

**Comment by omnidan** [comment]
@hex13 thank you so much for debugging and fixing this! - the only issue I see now is the comparison of arrays. Spread operation would be nice but is not essential to me. (and I understand it's not a standard so acorn isn't implementing it)

**Comment by omnidan** [comment]
@hex13 I tried updating it to your gist and removing the whitespace (check out the `unit-tests` branch) - it still does not work :/

```
SyntaxError: Unexpected token (2:4)
```

**Comment by pl12133** [comment]
Speck looks very nice but I know nothing about it. Do you have any desire to implement tests with chai? I've written a few tests for the undo/redo actions. Tests are [here](https://github.com/pl12133/redux-undo/blob/master/test/index.spec.js), and the results: ![redux-undo-tests.png](http://i.imgur.com/3zyHLwY.png)

I've never done a PR but if you would like I would be very happy to contribute!

**Comment by omnidan** [comment]
@pl12133 Thanks for writing tests :grin: That looks cool - chai should be fine too. 

Have a read of https://help.github.com/articles/using-pull-requests/ if you don't know how to do a PR and feel free to ask me questions if you run into issues :smile:

**Comment by pl12133** [comment]
@omnidan Great, I read up on using pull requests and opened one, thanks.

**Comment by omnidan** [comment]
solved in #20
