### ISSUE TITLE
How is limit supposed to work?

### ISSUE THREAD

**Issue by rolfnl** [omnidan/redux-undo#6]
Nice job, I just wondered how `limit` is supposed to work.
Testing with the counter example, if you set the limit to 4 and you do:
- plus + undo
- plus + undo
- plus + undo
- plus + undo

The last time (nr 4) doesn't work anymore. I would have expected this to work 4 times. Just like you would do 5x plus and then you can do 4x undo (and then it stops because of the limit).

Any idea?

**Comment by omnidan** [comment]
limit should "delete" (cut out) the oldest entry in your history - what exactly does not work? it doesn't undo?

**Comment by rolfnl** [comment]
I just cloned and run the demo/counter repo.

My expectations are that when I set a limit of 4 that there will be 4 history instances available.

This is also the case when you press the `plus` button 5 times and than the `undo` button it works 4 times, as expected. So it goes from 0 to 5 and then with the undo back to 1.

But when you click the `plus` button and then the `undo` button and repeat that 4 times the last time it doesn't work, it doesn't undo. The last 1 that should go to 0 doesn't go to 0.

**Comment by omnidan** [comment]
@rolfnl huh, that's really strange. I just did the exact same thing (cloned the boilerplate, `npm install`, `npm start`) and that doesn't happen to me. The last time it still undos for me.

Can you check which version of `redux-undo` and the boilerplate you have installed?

**Comment by omnidan** [comment]
I can see what the problem is here. It's more a lack of a feature than a bug. When you do that, at the last action, `0` gets thrown out of the history (because it's the oldest entry).

I think a way to get around that would be refreshing states when they get accessed again via undo/redo. I still have to think of a good way to do that, though.

**Comment by omnidan** [comment]
Alright, I structured history like an UndoList in elm: http://package.elm-lang.org/packages/TheSeamau5/elm-undo-redo/2.0.0/UndoList

This fixes this issue and should make undo/redo cleaner in general :)

Thanks a lot for reporting this issue!

**Comment by omnidan** [comment]
@rolfnl please update `redux-undo` and let me know if it works fine for you now :)

**Comment by rolfnl** [comment]
Actually, I was thinking about that Elm package but couldn't find it in my bookmarks and didn't remember it was something like `UndoList`. Anyway, great effort. I still run into a problem though.

Again, I cloned a fresh copy of the counter example repo that uses 0.3.0. When I set limit to 4 and hit the `plus` button 10 times, then hitting `undo` goes to 7 and then stops instead of 6.

Maybe it's a simple `>` vs `>=` check somewhere. Currently unable to check the src.

**Comment by omnidan** [comment]
First of all, thanks a lot for all your testing :+1:

I just checked and it does seem to work as it should. When you go up to 10, it will store the last 4 states, which are: 10, 9, 8, 7 (not 6). A solution to your problem would be setting the limit to 5 :P

**Comment by rolfnl** [comment]
:+1:
