### ISSUE TITLE
debug mode "hides" user console logs

### ISSUE THREAD

**Issue by peteruithoven** [omnidan/redux-undo#66]
Looks like when using redux-undo's debug mode the console.logs of users are "hidden" away in folded console.group's. 
![screenshot from 2016-03-18 12 26 23](https://cloud.githubusercontent.com/assets/523210/13876455/bf23cc18-ed04-11e5-9255-edcaa53dcdb3.png)

This could probably be solved by saving the logs and logging them all at once. 

This is a minor inconvenience, it's mostly confusing.

**Comment by tiemevanveen** [comment]
Fair point, maybe they could be stored and logged at the point where we close the group now .. 
https://github.com/omnidan/redux-undo/blob/master/src/index.js#L25

**Comment by pl12133** [comment]
This sounds like a valid problem to me. You should be able to log things inside your reducer and `redux-undo` shouldn't stop you.

@tiemevanveen has the right idea for this I believe. I tried implementing that idea on #68 to fix this issue.

**Comment by omnidan** [comment]
Should be resolved in beta7
