### ISSUE TITLE
Clarify debug logs

### ISSUE THREAD

**Issue by peteruithoven** [omnidan/redux-undo#67]
I would find it very usefull to get a better idea of what the following items in the debug logs of redux-undo mean:
- received
- insert
- after
Could this be clarified in the readme?

**Comment by pl12133** [comment]
I agree that these aren't very informative messages.

1. "received" prints the `(state, action)` that an `undoable` reducer has received.
2. "insert" prints the `newState` that is added to a history object.
3. "after" signifies that the state has changed and prints `newState`.

I would be happy to hear alternative messages, here are some proposals:

1. "(state, action)"
2. "insert newState"
3. "newState after ${action.type}"

**Comment by peteruithoven** [comment]
> "received" prints the `(state, action)` that an `undoable` reducer has received.

Very clear, thanks for explaining.

> "insert" prints the `newState` that is added to a history object.

If I understand you and the code correctly that state is the new present. It's the result of running the wrapped reducer with the received arguments. I find the name 'new present' clarifying here. 
But it also prints the pre-insert `history`, which I find confusing because it's placed after the word "insert". I would separate that, probably combined with `free`. 

I would go with something like: 
- `received: {state, action}`
- `prev: {history, free}`
- `new present: {present}` or `next present: present` (could also be retrieved from new/next below)
- `new: {history, free}` or `next: {history, free}`

The [redux-logger](https://www.npmjs.com/package/redux-logger) also uses `prev` and `next`.

**Comment by pl12133** [comment]
Nice idea @peteruithoven, I like the idea of using `prev, action, next` to show the `(state, action) => newState` of a reducer. I think showing those three things with a note regarding what the action did would be a lot of information for the user. I made these changes to the debug logging in #68 so now a debug statement looks like this:

```text
  prev history: { past: [], present: 'foo', future: [] }
  action: { type: 'bar' }
  next history: { past: [ 'foo' ], present: 'baz', future: [] }
    inserting 'baz'
    new free: 123
    inserted new state into history
```

**Comment by peteruithoven** [comment]
Like!
I like the way you're putting the history directly in the log (instead of in another object) it becomes more easily scannable.

**Comment by omnidan** [comment]
Being worked on in https://github.com/omnidan/redux-undo/pull/68

**Comment by omnidan** [comment]
Resolved in beta7
