### ISSUE TITLE
Dynamic reducer

### ISSUE THREAD

**Issue by benjasHu** [omnidan/redux-undo#69]
Hi!
I'm trying to implement a minigame in which I have this process:

- Fetch stage data
- User plays that stage
- Click on Next button and fetch next stage data
- Navigate to the new stage
- User plays new stage
- ...

How could I implement undoable reducer to every new stage in the way this new stage has its own history?

I mean, I have this:
```javascript
function stage( state={}, action ) {
	switch(action.type) {

		case GAME_SUCCESS:
			return merge({}, state, {
				[action.json.response.stage.id]: action.json.response.stage
			})

		default:
			return state
	}
}

function stages( state={}, action ) {
	switch(action.type) {

		case GAME_SUCCESS:
			return stage(state, action)

		default:
			return state
	}
}

export default combineReducers({
	stages: undoable(stages)
})
```
`stages()` is my undoable reducer and it works perfectly, but I only have one history for every stage... How could dynamically assign new undo to every new loaded stage?

Thanks!

**Comment by omnidan** [comment]
I think what you want is a way to clear the whole undo/redo state. Have you tried using the [`clearHistory` action](https://github.com/omnidan/redux-undo#undoredo-actions) or [specifying the `GAME_SUCCESS` action in the `initTypes` configuration](https://github.com/omnidan/redux-undo#configuration)?

**Comment by benjasHu** [comment]
Specifying `GAME_SUCCESS` action in the `initTypes` was the solution, thanks!

**Comment by benjasHu** [comment]
I noticed that `clearHistory` action is not present in @beta?

I've cleared npm cache and reinstalled with `npm install --save redux-undo@beta` and still returns undefined.

Looking inside the code in the downloaded package neither...

What am I doing wrong?

**Comment by omnidan** [comment]
@benjasHu Oh, it seems like it's not published yet but somehow slipped through into the README.md. Well, I plan on releasing the next beta soon, anyway - then it'll be available.

**Comment by omnidan** [comment]
@benjasHu I just published [`beta4`](https://github.com/omnidan/redux-undo/releases/tag/beta4), so `clearHistory` should work now - sorry for the inconvenience!

**Comment by benjasHu** [comment]
@omnidan just tested and works perfectly! Thanks!

**Comment by omnidan** [comment]
Glad to hear that it works - thanks for testing! :grin:
