### ISSUE TITLE
Combine filters 

### ISSUE THREAD

**Issue by peteruithoven** [omnidan/redux-undo#71]
Is there an easy way to combine multiple filter functions together? 
I noticed I was writing one function which performed 3 filters and I couldn't easily combine the existing helper filter functions. What if we create a combine function, something like below, that checks all filters: 
``` javascript
undoable(reducer, { filter: combineFilters(distinctState(), excludeAction(SOME_ACTION)) });
``` 
This, for edge cases, also allows usage inside a custom undoFilter:
``` javascript
undoable(reducer, { filter: undoFilter });
function undoFilter(action, currentState, previousState) {
  let filter = combineFilters(distinctState(), excludeAction(SOME_ACTION))(action, currentState, previousState);
  if(!filter) return filter; 
  // more filters
}
```

**Comment by omnidan** [comment]
@peteruithoven you're right, this is not currently possible. However, on the latest release `beta4`, there is no need for `distinctState()` anymore. Might be interesting as a helper though.

**Comment by peteruithoven** [comment]
It's mostly for when you want to combine filters for exclusion and different throttling techniques for example. I'll try to work on a pull request.

**Comment by Bear-Foot** [comment]
Hello there. @peteruithoven are you up to something about this ? I'd be glad to help if you are too busy.

**Comment by peteruithoven** [comment]
I'm afraid I haven't come around to it yet, I got stuck at figuring out how the unit tests worked. But through Gitter I did see [your gist](https://gist.github.com/Bear-Foot/fe40b7644de21ca25cbec8a48dcf2252) and [omnidan's fork](https://gist.github.com/omnidan/3432a5dc51e876e2803cc59998562c09), nice work!

**Comment by omnidan** [comment]
Resolved in beta7
