### ISSUE TITLE
Reset to oldest

### ISSUE THREAD

**Issue by iandanforth** [omnidan/redux-undo#76]
Use case: We've built an editor that uses redux-undo. If a user decides to exit from the editor without saving we want to reset our `present` to the state before any edits were made and clear out `past` and `future`. This is what we use today:
```javascript
case RESET_UNDO_HISTORY_TO_OLDEST:
    let present;
    if (state.past.length === 0) {
      present = state.present;
    } else {
      present = state.past[0];
    }
    newHistory = {
        past: [],
        present: present,
        future: []
    };
    return newHistory;
```

Perhaps a renamed and cleaned up version of this could be useful as part of the main lib.

**Comment by iandanforth** [comment]
Broken out from #38

**Comment by pl12133** [comment]
Hey @iandanforth, can you use the [jumpToPast action](https://github.com/omnidan/redux-undo/#undoredo-actions) with `{ index: 0 }` followed by a `clearHistory` action? I think that might be able to do what you are looking for.

**Comment by iandanforth** [comment]
Actually this turns out is a bad idea. Had users hit my defined history limit and got reset, not back to a clean state, but the oldest we had in the stack. Instead we now clear local state and re-populate from the server, then clear history.
