### ISSUE TITLE
Gracefully Deprecate `distinctState` filter

### ISSUE THREAD

**Issue by pl12133** [omnidan/redux-undo#79]
To make upgrading to 1.0.0 as easy as possible, we should replace the helper function `distinctState` with a function that returns the default filter, and prints to `console.error` showing that distinctState is deprecated and no longer needed.

**Comment by tiemevanveen** [comment]
I agree! Though, I like a Warnjng better 😊

**Comment by stantoncbradley** [comment]
+1 this upgrade breaks the Redux todos-with-undo example https://github.com/reactjs/redux/tree/master/examples/todos-with-undo
new to redux & redux-undo, what should ```distinctState``` be replaced with?

**Comment by tiemevanveen** [comment]
You can just leave it out. It is applied by default now

**Comment by stantoncbradley** [comment]
gotcha!  submiting a PR to Redux now!  Thanks @tiemevanveen

**Comment by omnidan** [comment]
Cool - I already updated the local example, btw :wink: https://github.com/omnidan/redux-undo/tree/master/examples/todos-with-undo

**Comment by stantoncbradley** [comment]
@omnidan nice.  the example works again thanks to the deprecation fix in 1.0.0-beta6.  For backwards compatibility I will leave the Redux example alone for now.  I think this issue is resoved :smile:

**Comment by omnidan** [comment]
Alright, thanks for everything :+1:
