### ISSUE TITLE
UMD support

### ISSUE THREAD

**Issue by weslleyaraujo** [omnidan/redux-undo#81]
For some applications the UMD support would be very useful,
it would be a nice improvement...

I am willing to write a PR for this, any objections? 

(btw, awesome work 🤘)

**Comment by omnidan** [comment]
@weslleyaraujo I haven't looked at UMD at all yet, but feel free to send a PR and I'll check it out :smile:

**Comment by weslleyaraujo** [comment]
cool I will work on that :)

**Comment by omnidan** [comment]
Resolved in beta7
