### ISSUE TITLE
multiple history stacks for parts of the entire state? 

### ISSUE THREAD

**Issue by goodhyun** [omnidan/redux-undo#84]
Let's say there is a text editor with multiple tabs. 
Each tab is supposed to hold its own history stack, but redux recommends all the state should be in a single store. If you are editing several tabs, continuous undos will mess around with contents in other tabs, in case a same reducer is accessing several content arrays.

Preparing an array of separate stacks for state[0], state[1], and state[n] can be a solution ?

Is it possible to solve this use-case, or should we build a custom traditional undo stack for each members of array?

**Comment by peteruithoven** [comment]
It's possible to have multiple undo stacks, this should work with multiple (array) items as well. 
Because the amount is dynamic you might want to use a extra action parameter, for example `tabIndex`, to specify which tab should be reduced by undo. 
Couldn't the following work? 
``` javascript
// respond to tab specific (and possibly undo) actions: 
state.tabs[action.tabIndex] = undoable(state.tabs[action.tabIndex], action);
```

**Comment by goodhyun** [comment]
Thanks for the insight. 

Splitting a reducer again for a micro reducer whose main goal was only to accessing members of array was the solution. Now, I was able to set 'undoable' for this splitted reducer and combine them in my own way.
