### ISSUE TITLE
Is it possible to 'sync' histories?

### ISSUE THREAD

**Issue by fetimo** [omnidan/redux-undo#85]
Apologies for masquerading a question for an issue but I wasn't sure where else to post this. My use case is that I have two distinct pieces of state handled by separate reducers. When the user initiates an action I want to undo both histories to n but stateA could have 10 history items and stateB only have 5.

I think one solution for me would be to save a guid with each history item and write some custom logic to filter where these match e.g. stateA is rewound to -2 and stateB to -1. The other option would be to include all the needed state information together but this doesn't feel very 'Reduxy'.

Does redux-undo support anything that would support this currently?

**Comment by peteruithoven** [comment]
Could you elaborate on why you'd like to rewind stateA to -2? 
Are you sure you can't create two undo reducers that both listen to the same undo action?

**Comment by fetimo** [comment]
Hi Peter, thanks for replying. They're currently two separate undo reducers. I'm building up a list of links visited, when the user clicks back into one of those links the app should 'time travel' back to how the site was at that point (search term, filters chosen, that sort of thing). My issue is the search term (stateA) could have many more history entries, e.g.: 

`search: {
  ...  
  past: ['My initial search term'], ['s'], ['s', 'e'], ['s', 'e', 'a']
}`

Whereas visitedLinks (stateB) may be:

`visitedLinks: {
  ...
  past: [{url: '/home'}], [{url: '/search'}, [{url: '/article/sea'}]]
}`

Say the user clicks a link to 'search', in this case trying to figure out which pieces of each past stream to go to can become confusing. Does that make sense so far?

Maybe I need to separate it out a bit so only the last search term before navigation is added or something.

**Comment by peteruithoven** [comment]
Sounds like they should be part of the same history, so you can travel back like:
- url:/article/sea
- url:/search, search:sea
- url:/search, search:se
- url:/search, search:s
- url:/home

I think the easiest way, to do this is to put both search and visitedLinks into one undo reducer. 
Another idea might be to include the search into the url, as a query parameter, then your url can be leading, you might even be able to simply use the react-router-redux.

**Comment by tiemevanveen** [comment]
We discussed this on Gitter a while back: https://gitter.im/omnidan/redux-undo?at=56e31581c7364f7926be2f44 / https://gitter.im/omnidan/redux-undo?at=56e4553ac7364f7926be63ae

I had the same problem as you describe and ended up wrapping my root reducer in undoable.

**Comment by omnidan** [comment]
I think this might help too: https://github.com/omnidan/redux-undo/issues/77 - we really need to get the FAQ page (with common patterns like this one) done :sweat_smile:

**Comment by omnidan** [comment]
Closing this as it's been superseded by #88 - feel free to comment there, reopen or open a new issue if you feel it's necessary :wink:

**Comment by fetimo** [comment]
Thanks for all the help all.

FWIW the solution I went with was to refactor it as per @peteruithoven into one undo reducer but also save the _length_ of the past array so rewinding it to that point is as simple as `ActionCreators.jumpToPast(visitedLinks[index].past)`.
