### ISSUE TITLE
Ability to restore history?

### ISSUE THREAD

**Issue by alex-wilmer** [omnidan/redux-undo#91]
Not sure if there was an existing way to do this, but I didn't see one. I'm saving my entire state object to DB and would like to load the entire history (past, present and future). I ended up wrapping `undoable` in this:

```js
function reinstate (reducer) {
  return function (state, action) {
    switch (action.type) {
      case REINSTATE:
        return {
          ...action.payload
        }
      default:
        return reducer(state, action)
    }
  }
}
```

it's exactly what I need. Does `redux-undo` already cover this somewhere / if not, would a PR including something like this be appreciated?

**Comment by omnidan** [comment]
@alex-wilmer yes, this is possible. Just [pass your `initialState` to `createStore`](https://github.com/omnidan/redux-undo#initial-state-and-history)

```js
import { createStore } from 'redux';

const initialHistory = {
  past: [0, 1, 2, 3],
  present: 4,
  future: [5, 6, 7]
}

const store = createStore(undoable(counter), initialHistory)
```

**Comment by alex-wilmer** [comment]
Thanks for the response, I'm a little unsure how this works with `combineReducers` however. I only have a very small part of my state tree using `undoable`. Also in your example doing this inside `createStore` would happen only on page load correct as opposed to on an user caused action?

```
let finalReducer = combineReducers({
  ...
  transport: reduceTransport,
  phrase: reinstate(undoable(reducePhrase, { filter: excludeAction(phrase.LOAD) })),
  ..
})
```

**Comment by omnidan** [comment]
@alex-willmer Oh, I see. That's a different use-case, you might want to use [redux-recycle](https://github.com/omnidan/redux-recycle) for that. It works similar to your `reinstate` function. The idea of higher-order reducers is to have small reusable blocks, so I decided to split this main project into smaller ones: [redux-undo](https://github.com/omnidan/redux-undo), [redux-ignore](https://github.com/omnidan/redux-ignore) and [redux-recycle](https://github.com/omnidan/redux-recycle)

BTW: Combining higher-order reducers is a much better pattern than having a single one that does everything, so don't worry about having to write your own higher-order reducers sometimes. You might even want to release it as a library if it doesn't exist yet and you think it might be useful for others. :wink:
