### ISSUE TITLE
Null entry in past array with 1.0-beta8

### ISSUE THREAD

**Issue by tjunnone** [omnidan/redux-undo#95]
After upgrading to 1.0-beta8 (from beta7), I'm always getting a null item as the first entry in the "past" array after the first action, not sure why. Checking for this everywhere would be quite cumbersome.

Revering back to beta7 fixed the issue for me, seems like a regression or at least an unexpected change in behavior.

**Comment by omnidan** [comment]
@tjunnone This is actually an intended behaviour change (see #86 for more information why this change was made).

The new behaviour works like this:

```
ACTION 1 -> result stored in present
ACTION 2 -> old result stored in past, new result stored in present
```

Which is not the same as the beta7 behaviour, but it makes more sense to me. Is this causing any issues with your project?

**Comment by tjunnone** [comment]
I think the behavior in #86 makes sense as I understand it, I'm specifically troubled by the initial null entry now moving to the past array on the first action even if that action itself was filtered. E.g:

Redux INIT -> present: null, past: []
LOAD (filtered: true) -> present: {state1}, past: [null]
DO_SOMETHING -> present: {state2}, past: [null]
DO_SOMETHING -> present: {state3}, past: [state2, null]

The presence of the null entry in the past array gives in my opinion unintuitive answers to questions like "how many undo entries are there?" and I now need to filter it out in every place that can access the past.

**Comment by tiemevanveen** [comment]
I agree that this is not intuitive. I did not see the null entries when testing beta8.. Should have been caught in the unit tests right?..

**Comment by omnidan** [comment]
@tjunnone I see, that shouldn't happen. I think this is an edge-case when the initial state is `null` (which still gets stored because `wasFiltered` isn't `true`)

Can you put up a small example or maybe even a failing unit test?

**Comment by joshkel** [comment]
I'm seeing a similar problem: I'm always getting an empty object as `past[0]`. This wasn't the case in beta7. I think the problem is that, if the first action that redux-undo sees is filtered, then it goes ahead and pushes the (unknown/uninitialized) state to `past`. Previous versions completely ignored filtered actions, so `past` only contained initialized, valid states. Like @tjunnone, we relied on the ability to check `past.length` to see how many undo entries there are, so this is causing problems.

**Comment by EugeneHlushko** [comment]
@tjunnone @joshkel I cannot make filtering work, in console it says: 'filter prevented action, not storing it' 
but i actually get a history record and can undo. Guess this is related to what you have described

**Comment by arvind** [comment]
I've experienced this as well, and I don't think it's specific to `null` initial states. Rather, if the very first action after initialization is filtered, this library currently adds `present` (initial state) to `past`, and marks the _new_ `present` as `wasFiltered`. This gives the appearance of a past state, which disappears if one performs an undo action. 

Instead, perhaps `wasFiltered` should only be set if the `config.filter` function returns `false` _and_ `past.length === 0`?

**Comment by peteruithoven** [comment]
@arvind could you maybe create a small example? Something we can run and experiment with.

**Comment by davidroeca** [comment]
I was facing the same issues. I've fixed this in https://github.com/omnidan/redux-undo/pull/139, by setting the ignoreInitialState flag to true in the config

**Comment by omnidan** [comment]
I published a new version `beta9-3` that should fix this issue (thanks a lot, @davidroeca :tada:)

Let me know if it works now and feel free to reopen if you're still having issues! :grin:

**Comment by camsjams** [comment]
This change was not added to the README unfortunately, so requires a little dive thru the code to unearth `ignoreInitialState`

**Comment by omnidan** [comment]
@camsjams could you send a PR completing the README with this feature? :grin:

**Comment by camsjams** [comment]
Yep I plan to - expect it Monday

**Comment by camsjams** [comment]
Added PR https://github.com/omnidan/redux-undo/pull/177
