### ISSUE TITLE
VSCode don't like ... object extend

### ISSUE THREAD

**Issue by katopz** [omnidan/redux-undo#97]
For some reason VSCode didn't like [this line](https://github.com/omnidan/redux-undo/blob/master/src/reducer.js#L215).
![screen shot 2559-05-20 at 11 24 54](https://cloud.githubusercontent.com/assets/97060/15417240/b86d8f30-1e7d-11e6-9c4e-208927dc7961.png)

Which is also throw error in chrome if I try to use from source directly (Yes I shouldn't but I'm curious).
I try to warp my head around this `...` shorthand for extend object but can't find any replacement to avoid this.

And yes nothing break if I use compiled one. I'm just curious and can't sleep well because of this.
You can close this if it look stupid anyway. Just my bad habit is issue here!

**Comment by pl12133** [comment]
Hey there @katopz,

For a little more about that operator, it is called the [Object Rest/Spread Operator](https://github.com/sebmarkbage/ecmascript-rest-spread#object-restspread-properties-for-ecmascript). It is another syntax for the `Object.assign` function. You can compile the Object Rest/Spread Operator using the [babel-plugin-transform-rest-spread](https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread) package for Babel. To avoid using it, you can stick with `Object.assign`. If you need to support an environment that does not have access to Object.assign, you can use [babel-plugin-transform-object-assign](https://babeljs.io/docs/plugins/transform-object-assign/) plugin for Babel, or you can polyfill `Object.assign` with the [MDN Object.assign polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill).

Hopefully now you can sleep!

**Comment by katopz** [comment]
That's a lot better than any lullaby songs, Thanks! :)
