### ISSUE TITLE
Problems from #86

### ISSUE THREAD

**Issue by joshkel** [omnidan/redux-undo#98]
I'm testing out beta8 and am trying to understand the changes from #86 and have run into a few related problems.

First, I'm seeing the same problem as #95. 

Second, if the first action is filtered, and for the first filtered action after an unfiltered action, redux-undo pushes an entry to `past` and sets `wasFiltered` (so that later operations won't keep adding entries). The disadvantage here is that it interferes with tracking `past.length` to know how many undo operations can be done.

Third, if a filtered action follows an unfiltered action, the current state is stored to `past` with `wasFiltered` true, but if I then undo, it undoes the most recent `past` - in other words, it undoes to the state before the filtered action, instead of undoing what I actually care about.

A possible solution to these problems: Instead of tracking `wasFiltered` (a bool) and using the most recent entry in `past`, track `_latestUnfiltered` 
- Whenever an unfiltered action occurs, store it to `_latestUnfiltered` (as well as doing normal history actions).
- When inserting to history, insert from `_latestUnfiltered` (if that's been defined) instead of `present`.

I'm happy to try to work up a PR and unit tests if you're interested (although I'm getting ready to go on vacation, so it may be a couple of weeks).

**Comment by peteruithoven** [comment]
Just like I experienced with #86 these things are very hard to explain, is this about a different case than your explaining in #86?

**Comment by joshkel** [comment]
It's a different set of problems than #92 . Sorry I wasn't clearer.

I'm having trouble getting beta8 to work at all, due to strange behavior with an empty initial object (#95), strange behavior with `past.length` (my second problem above), and undo simply not working if an unfiltered action followed a filtered action (my third problem above). So this issue is regarding that.

Even after these problems are fixed, if I understand things correctly, the behavior changes in #86 won't be what I want, for reasons which I tried to explain in my comments there.

**Comment by peteruithoven** [comment]
Could you also make a working technical example that demonstrates those issues?

**Comment by davidroeca** [comment]
I had a similar issue--my current application is a bit complicated, as it uses the latest redux form with immutablejs. 

I've noticed that my main problem is that unfiltered actions get stored too early. Redux form does a lot of heavy lifting and maintains its own internal state with thunks, so immediately saving an unfiltered action during a fire of a filtered action will cause problems (as it also does in the current beta release with undos destroying the future array if they cause subsequent filtered thunk actions).

Basic example:
Action A = unfiltered action
Action F = filtered action (typically fired by a thunk for redux form's internal state)

Current state:
1: Action A happens
2: Action F happens <--- line 1's state is added to past
3: Action F happens
4: Action A happens
5: Action F happens <--- line 4's state is added to past
6. Action A happens

Ideal state:
1: Action A happens <--- snapshot of "most recent unfiltered state" is taken
2: Action F happens
3: Action F happens
4: Action A happens <--- line 1's state is added to past; snapshot of "most recent unfiltered state" is taken
5: Action F happens
6. Action A happens <--- line 4's state is added to past; snapshot of "most recent unfiltered state" is taken

Here's a current work in progress with the second scenario implemented
https://github.com/omnidan/redux-undo/compare/master...davidroeca:dev

**Comment by davidroeca** [comment]
New PR based on the above
https://github.com/omnidan/redux-undo/pull/139

**Comment by omnidan** [comment]
I published a new version `beta9-3` that should fix this issue (thanks a lot, @davidroeca :tada:)

Let me know if it works now and feel free to reopen if you're still having issues! :grin:

**Comment by peteruithoven** [comment]
Great improvement people! We (who opened #86) just figured out we where running into the same issue.
